"""Transfer function estimation from exponential sine sweeps (ESS).

The excitation is generated on the device by the `SweptSine` signal source of the
`dual-iir` firmware (`idsp::Sweep` driving an `idsp::AccuOsc`), which is added to the DAC
output of a channel. As the stimulus is known exactly, the responses of all streamed
channels can be deconvolved with it (Farina's method). In the resulting impulse
responses, the harmonic distortion products appear before the linear response, so that
they can be separated by windowing. For the start frequency we use an integer number of
cycles per harmonic delay ("synchronized" swept sine, Novák et al., JAES 63, 786 (2015)),
which gives the harmonic impulse responses a well-defined phase.

The analysis itself (`analyse()`) is implemented in Rust in the `stabilizer_psd`
extension (`psd/src/ess.rs`, `stabilizer_psd.analyse_sweep()`), as it is heavy. The
extension also reproduces the excitation exactly (`Sweep.excitation()`), with the
firmware's own oscillator. This module holds the sweep design, the settings and result
types, and the quantities derived from the responses.

All frequencies are in Hz and all times in seconds unless noted otherwise.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

import numpy as np
import stabilizer

try:
    import stabilizer_psd as _psd
except ImportError:  # The extension is optional (it needs a Rust toolchain to build).
    _psd = None

#: Fixed-point scale of the firmware sweep rate (`1 + rate / 2^32` is the per-sample
#: frequency growth factor) and of the frequency state (`state / 2^64` is the frequency
#: in cycles/sample).
_Q = 1 << 32

#: Maximum stop frequency, in cycles/sample. The 64-bit frequency state overflows at
#: Nyquist.
MAX_STOP_FREQUENCY = 0.49

#: DAC full scale (`DacCode::FULL_SCALE` in the firmware), in volts. The excitation is
#: added to the DAC output in machine units, so its amplitude must stay below this.
DAC_FULL_SCALE = np.float32(4.096) * np.float32(2.5)
MAX_AMPLITUDE = float(DAC_FULL_SCALE)
#: Volts per DAC code of `Sweep.excitation()`: the scale of the captured stream data,
#: from which the excitation is subtracted (not the single precision full scale above,
#: which differs by 7e-8).
DAC_VOLTS_PER_LSB = stabilizer.DAC_VOLTS_PER_LSB

#: Width of the raised-cosine tapers at either end of the analysis band, in octaves (as
#: in `psd/src/ess.rs`). No results are reported for these regions.
BAND_EDGE_TAPER = 1 / 12


class AnalysisError(Exception):
    """The captured data could not be analysed."""


def _extension():
    if _psd is None:
        raise ImportError("The analysis needs the stabilizer-psd package (in psd/)")
    return _psd


@dataclass(frozen=True)
class Sweep:
    """An exponential sweep, as generated by the firmware `SweptSine` source.

    The firmware outputs `amplitude * sin(2π φ[n])` for `0 <= n < length` (and zero
    afterwards). `state` holds the instantaneous frequency in units of 2^-64
    cycles/sample and is multiplied by `1 + rate / 2^32` every sample, so that the phase
    in turns is approximately

        φ[n] = cycles * ((1 + rate / 2^32)^n - 1),   cycles = state / (2^32 rate).
    """

    #: Frequency growth rate (`Sweep::rate`).
    rate: int
    #: Initial frequency in units of 2^-64 cycles/sample (`Sweep::state`).
    state: int
    #: Number of samples.
    length: int
    #: Amplitude, in volts.
    amplitude: float
    #: Sample period, in seconds.
    sample_period: float

    @classmethod
    def design(cls, f_start: float, f_stop: float, duration: float, amplitude: float,
               sample_period: float) -> Sweep:
        """Find the firmware sweep parameters closest to the given ones.

        As the number of cycles per harmonic delay is rounded to an integer (at least
        one), the actual start frequency can differ from `f_start`; short sweeps cannot
        start at frequencies below about `ln(f_stop / f_start) / duration`. The length is
        then chosen to end the sweep at `f_stop`.
        """
        f1 = f_start * sample_period
        f2 = f_stop * sample_period
        if not 0 < f1 < f2:
            raise ValueError("Start frequency must be positive and below the stop "
                             "frequency")
        if f2 > MAX_STOP_FREQUENCY:
            raise ValueError("Stop frequency must be below "
                             f"{MAX_STOP_FREQUENCY / sample_period:.0f} Hz")
        if not 0 < abs(amplitude) < MAX_AMPLITUDE:
            raise ValueError(f"Amplitude must be between 0 and {MAX_AMPLITUDE} V")

        n = duration / sample_period
        if n < 1:
            raise ValueError("Duration too short")
        rate = round(_Q * math.expm1(math.log(f2 / f1) / n))
        if not 1 <= rate < (1 << 31):
            raise ValueError("Sweep rate out of range; adjust the duration")
        growth = math.log1p(rate / _Q)
        cycles = max(1, round(f1 / growth))
        f1 = cycles * growth
        if f1 >= f2:
            raise ValueError("Duration too short for the requested frequency range")
        length = round(math.log(f2 / f1) / growth)
        if length >= (1 << 32):
            raise ValueError("Sweep too long")
        return cls(rate, rate * cycles * _Q, length, float(amplitude), sample_period)

    @property
    def growth(self) -> float:
        """Exponential growth rate of the instantaneous frequency, per sample."""
        return math.log1p(self.rate / _Q)

    @property
    def cycles(self) -> float:
        """Number of cycles per harmonic delay (`f_start` times the e-folding time)."""
        return self.state / (_Q * self.rate)

    @property
    def f_start(self) -> float:
        return self.cycles * self.growth / self.sample_period

    @property
    def f_stop(self) -> float:
        return self.f_start * math.exp(self.growth * self.length)

    @property
    def duration(self) -> float:
        return self.length * self.sample_period

    def harmonic_delay(self, k: float) -> float:
        """Time by which the k-th harmonic of the sweep leads the fundamental, in samples.

        For an integer number of cycles, `sin(k φ[n]) = sin(φ[n + harmonic_delay(k)])`.
        """
        return math.log(k) / self.growth

    def excitation(self) -> np.ndarray:
        """The excitation added to the DAC output, in volts, exactly as the firmware
        generates it: the extension runs the firmware's oscillator (including its
        fixed-point phase and sine table) and the scaling to DAC codes, so this needs
        `available()`.
        """
        return _extension().sweep_excitation(self._parameters())

    def _parameters(self) -> tuple:
        """The sweep as passed to the extension."""
        return (self.rate, self.state, self.length, self.amplitude, self.sample_period)

    def source_config(self) -> dict:
        """The settings of the firmware signal source (`ch/<n>/source/...`)."""
        return {
            "signal": "SweptSine",
            "amplitude": self.amplitude,
            "offset": 0.0,
            "length": self.length,
            "state": self.state,
            "rate": self.rate,
            # Unused for sweeps, but validated by the firmware for all signal types.
            "frequency": 1e3,
            "symmetry": 0.5,
            "phase": 0.0,
        }


@dataclass(frozen=True)
class AnalysisSettings:
    #: Length of the window applied to the linear impulse response, in seconds. This
    #: sets the frequency resolution (and thus the lowest usable frequency, and how
    #: sharp resonances can be resolved), but longer windows also collect more noise.
    ir_window: float
    #: Number of points per decade of the logarithmic frequency grid. The responses are
    #: averaged over the frequency interval each point represents, so this also sets the
    #: amount of smoothing.
    points_per_decade: int = 100
    #: Highest harmonic order for which the response is computed.
    max_harmonic: int = 4


def default_ir_window(sweep: Sweep) -> float:
    """Impulse response window covering ten periods of the start frequency."""
    return min(max(10 / sweep.f_start, 2e-3), 1.0)


def capture_tail(ir_window: float) -> float:
    """Time to keep capturing after the end of the sweep, in seconds.

    This covers the response to the end of the sweep and the window used for the
    noise estimate (which follows the impulse response window).
    """
    return 2.7 * ir_window + 0.02


@dataclass
class Analysis:
    """The results for each channel of the captured data. After the captured channels,
    the results include an additional channel: the reference channel with the
    excitation subtracted (for the DAC of the excited channel, the IIR filter output).
    """

    #: Frequencies of the results, in Hz.
    frequencies: np.ndarray
    #: Complex response of each channel relative to the stimulus, (n_channels, n_freq).
    responses: np.ndarray
    #: Estimated noise (1σ) of `responses`, or NaN if not available.
    noise: np.ndarray
    #: For each harmonic order k, the fundamental frequencies at which the harmonic
    #: responses are available, in Hz.
    harmonic_frequencies: dict[int, np.ndarray]
    #: For each harmonic order k, the complex response of each channel at k times the
    #: fundamental frequency, (n_channels, n_freq_k); NaN where lost stream data affects
    #: it.
    harmonics: dict[int, np.ndarray]
    #: Estimated noise (1σ) of `harmonics`, or NaN if not available.
    harmonic_noise: dict[int, np.ndarray]
    #: Time axis of `impulse_responses`, relative to the start of the sweep.
    ir_time: np.ndarray
    #: Impulse responses (unwindowed) of each channel, (n_channels, n_time).
    impulse_responses: np.ndarray
    #: Window applied to the linear impulse response (start, stop), in s.
    ir_window: tuple[float, float]
    #: Window used for the noise estimate (start, stop), in s.
    noise_window: tuple[float, float] | None
    #: Windows used for the harmonics (start, stop), in s.
    harmonic_windows: dict[int, tuple[float, float]]
    #: Position of the start of the sweep in each run, in samples.
    offsets: list[int]
    warnings: list[str] = field(default_factory=list)

    @property
    def n_runs(self) -> int:
        return len(self.offsets)


def available() -> bool:
    """Whether `analyse()` is available, i.e. the `stabilizer_psd` extension is."""
    return _psd is not None


def _format_frequency(f: float) -> str:
    return f"{f / 1e3:.3g} kHz" if f >= 1e3 else f"{f:.3g} Hz"


def analyse(runs: list[np.ndarray],
            sweep: Sweep,
            reference: int,
            batch_size: int,
            settings: AnalysisSettings,
            offsets: list[int] | None = None,
            gaps: list[np.ndarray] | None = None,
            memory: int = 2 << 30) -> Analysis:
    """Estimate the responses of all channels to the sweep, averaged over several runs
    (`stabilizer_psd.analyse_sweep()`, see `psd/src/ess.rs` for the method).

    :param runs: For each run, the captured data of all channels, (n_channels, length),
        in volts.
    :param reference: Index of the channel containing the stimulus directly (the DAC
        output of the excited channel), used to locate the sweep start.
    :param batch_size: The stream batch size; the sweep starts at a batch boundary.
    :param offsets: The start of the sweep in each run, if already known.
    :param gaps: For each run, the ranges of samples (start, stop) which were lost and
        have been interpolated linearly, as an (n, 2) array. The response to the
        stimulus lost during the sweep is filled in from the response, and the noise
        estimate and the harmonics of the run are left out at the frequencies affected
        by what remains.
    :param memory: Memory budget for the buffers of the channels analysed in parallel,
        in bytes.
    :raises ImportError: if the extension is not available (see `available()`).
    :raises AnalysisError: if the data cannot be analysed.
    """
    try:
        result = _extension().analyse_sweep(
            [np.ascontiguousarray(run, np.float64) for run in runs],
            sweep._parameters(),
            reference,
            batch_size,
            settings.ir_window,
            settings.points_per_decade,
            settings.max_harmonic,
            offsets=None if offsets is None else [int(o) for o in offsets],
            gaps=None if gaps is None else
            [np.ascontiguousarray(np.asarray(g, np.int64).reshape(-1, 2)) for g in gaps],
            memory=memory)
    except ValueError as e:
        raise AnalysisError(str(e)) from None
    ts = sweep.sample_period
    orders = result["harmonic_orders"]
    ir_start = result["ir_start"]
    ir_window = result["ir_window"]
    noise_window = result["noise_window"]
    warnings = list(result["warnings"])
    gaps_at = [_format_frequency(f / ts) for f in result["gap_frequencies"]]
    if gaps_at:
        where = (f"at {', '.join(gaps_at)}" if len(gaps_at) <= 3 else
                 f"{len(gaps_at)} times between {gaps_at[0]} and {gaps_at[-1]}")
        warnings.append(f"Stream data lost during the sweep {where} (filled in from the "
                        "response; left out of the noise estimate)")
    return Analysis(
        frequencies=result["frequencies"] / ts,
        responses=result["responses"],
        noise=result["noise"],
        harmonic_frequencies={
            k: f / ts
            for k, f in zip(orders, result["harmonic_frequencies"])
        },
        harmonics=dict(zip(orders, result["harmonics"])),
        harmonic_noise=dict(zip(orders, result["harmonic_noise"])),
        ir_time=(ir_start + np.arange(result["impulse_responses"].shape[1])) * ts,
        impulse_responses=result["impulse_responses"],
        ir_window=(ir_window[0] * ts, ir_window[1] * ts),
        noise_window=None if noise_window is None else
        (noise_window[0] * ts, noise_window[1] * ts),
        harmonic_windows={
            k: (w[0] * ts, w[1] * ts)
            for k, w in zip(orders, result["harmonic_windows"])
        },
        offsets=list(result["offsets"]),
        warnings=warnings,
    )


#: Quantities derived from the responses, relative to the excited channel `n`.
#: The firmware adds the stimulus `s` to the output `y` of the IIR filter `C`, so that
#: `DAC = y + s = C ADC + s`. With the plant `P` (from DAC to ADC of the same channel),
#: the (negative feedback) loop gain is `L = -C P`, and `DAC / s = 1 / (1 + L)`.
QUANTITIES = {
    "plant": "Plant P = ADC{n} / DAC{n}",
    "loop": "Loop gain L = −CP = −y / DAC{n}",
    "controller": "Controller C = y / ADC{n}",
    "sensitivity": "Sensitivity 1 / (1 + L) = DAC{n} / s",
    "complementary": "Complementary sensitivity L / (1 + L) = −y / s",
    "adc": "ADC{n} / s",
    "adc_other": "ADC{m} / s (other channel)",
    "dac_other": "DAC{m} / s (other channel)",
}


def filter_output_name(n: int) -> str:
    """Name of the filter output `y` (the DAC output without the stimulus) of channel `n`
    in the `responses` passed to `derived_quantity()`."""
    return f"Y{n}"


def derived_quantity(quantity: str, responses: dict, noise: dict,
                     n: int) -> tuple[np.ndarray, np.ndarray]:
    """Compute one of `QUANTITIES` and its (first-order) noise estimate.

    :param responses: The response to the stimulus `s` of each channel (complex arrays),
        by channel name (`ADC0`, `DAC1`, …, and the filter output `y`, see
        `filter_output_name()`).
    :param noise: The noise estimates of `responses`, by channel name.
    :param n: The excited channel.
    """
    m = 1 - n
    adc, adc_noise = responses[f"ADC{n}"], noise[f"ADC{n}"]
    dac, dac_noise = responses[f"DAC{n}"], noise[f"DAC{n}"]
    y, y_noise = responses[filter_output_name(n)], noise[filter_output_name(n)]

    def ratio(a, a_noise, b, b_noise):
        # (The relative form, |a / b| hypot(a_noise / |a|, b_noise / |b|), is not
        # defined where a is exactly zero, e.g. the filter output of a blocked IIR.)
        value = a / b
        b_abs = np.abs(b)
        return value, np.hypot(a_noise / b_abs, np.abs(a) * b_noise / b_abs**2)

    with np.errstate(divide="ignore", invalid="ignore"):
        if quantity == "plant":
            return ratio(adc, adc_noise, dac, dac_noise)
        if quantity == "loop":
            return ratio(-y, y_noise, dac, dac_noise)
        if quantity == "controller":
            return ratio(y, y_noise, adc, adc_noise)
        if quantity == "sensitivity":
            return dac, dac_noise
        if quantity == "complementary":
            return -y, y_noise
        if quantity == "adc":
            return adc, adc_noise
        if quantity == "adc_other":
            return responses[f"ADC{m}"], noise[f"ADC{m}"]
        if quantity == "dac_other":
            return responses[f"DAC{m}"], noise[f"DAC{m}"]
    raise ValueError(f"Unknown quantity '{quantity}'")


def quantity_label(quantity: str, n: int) -> str:
    return QUANTITIES[quantity].format(n=n, m=1 - n)


#: For each of the `QUANTITIES`, the channel whose harmonics are shown, and the channel
#: whose (fundamental) response they are normalised to (None for the stimulus).
HARMONIC_CHANNELS = {
    "plant": ("ADC{n}", "DAC{n}"),
    "loop": ("Y{n}", "DAC{n}"),
    "controller": ("Y{n}", "ADC{n}"),
    "sensitivity": ("DAC{n}", None),
    "complementary": ("Y{n}", None),
    "adc": ("ADC{n}", None),
    "adc_other": ("ADC{m}", None),
    "dac_other": ("DAC{m}", None),
}


def derived_harmonic(quantity: str, harmonics: dict, harmonic_noise: dict,
                     responses: dict, frequencies: np.ndarray,
                     harmonic_frequencies: np.ndarray,
                     n: int) -> tuple[np.ndarray, np.ndarray]:
    """The harmonic response corresponding to one of `QUANTITIES`, and its noise.

    This is the harmonic response of the output channel of the quantity (at k times the
    fundamental frequency), normalised like the quantity, e.g. for the plant, the ADC
    harmonic relative to the DAC fundamental. Its ratio to the quantity is thus the
    harmonic distortion of that channel. (Only the magnitude is meaningful.)

    :param harmonics: The k-th harmonic response of each channel, by channel name.
    :param harmonic_noise: The noise estimates of `harmonics`.
    :param responses: The (fundamental) responses of each channel, at `frequencies`.
    :param harmonic_frequencies: The fundamental frequencies of `harmonics`.
    """
    output, reference = (None if name is None else name.format(n=n, m=1 - n)
                         for name in HARMONIC_CHANNELS[quantity])
    value, noise = harmonics[output], harmonic_noise[output]
    if reference is not None:
        log_f = np.log(harmonic_frequencies)
        response = responses[reference]
        reference = (np.interp(log_f, np.log(frequencies), response.real) +
                     1j * np.interp(log_f, np.log(frequencies), response.imag))
        with np.errstate(divide="ignore", invalid="ignore"):
            value, noise = value / reference, noise / np.abs(reference)
    return value, noise
