"""Transfer function estimation from exponential sine sweeps (ESS).

The excitation is generated on the device by the `SweptSine` signal source of the
`dual-iir` firmware (`idsp::Sweep` driving an `idsp::AccuOsc`), which is added to the DAC
output of a channel. As the stimulus is known exactly, the responses of all streamed
channels can be deconvolved with it (Farina's method). In the resulting impulse
responses, the harmonic distortion products appear before the linear response, so that
they can be separated by windowing. For the start frequency we use an integer number of
cycles per harmonic delay ("synchronized" swept sine, Novák et al., JAES 63, 786 (2015)),
which gives the harmonic impulse responses a well-defined phase.

All frequencies are in Hz and all times in seconds unless noted otherwise; internally,
frequencies are in cycles/sample and times in samples.
"""

from __future__ import annotations

import array
import math
from dataclasses import dataclass, field
from functools import partial

import numpy as np
from scipy import fft as sfft

#: Fixed-point scale of the firmware sweep rate (`1 + rate / 2^32` is the per-sample
#: frequency growth factor) and of the frequency state (`state / 2^64` is the frequency
#: in cycles/sample).
_Q = 1 << 32

#: Maximum stop frequency, in cycles/sample. The 64-bit frequency state overflows at
#: Nyquist.
MAX_STOP_FREQUENCY = 0.49

#: DAC full scale (`DacCode::FULL_SCALE` in the firmware), in volts. The excitation is
#: added to the DAC output in machine units, so its amplitude must stay below this.
DAC_FULL_SCALE = np.float32(4.096) * np.float32(2.5)
MAX_AMPLITUDE = float(DAC_FULL_SCALE)
DAC_VOLTS_PER_LSB = MAX_AMPLITUDE / (1 << 15)

#: Width of the raised-cosine tapers at either end of the analysis band, in octaves.
#: No results are reported for these regions.
BAND_EDGE_TAPER = 1 / 12

#: Regularisation of the inverse filter, relative to the expected sweep power spectral
#: density.
_REGULARISATION = 1e-4

#: Fraction of the impulse response window over which it is faded out.
_FADE_OUT = 0.25

#: Margin, in octaves, around the frequencies at which a window of the impulse response
#: receives the record at the time of lost data (see `_affected()`), for the spectral
#: leakage of the window.
_GAP_MARGIN = 1 / 24

#: Maximum number of passes of filling in lost data from the estimated response
#: (`fill_gaps()` in `analyse()`), and the relative change of the fill at which to stop.
#: Each pass reduces what remains by the relative error of the response estimate at the
#: frequency of the sweep at the time of the loss, which is the fraction of the
#: data lost there (within the frequency resolution).
_GAP_FILL_PASSES = 8
_GAP_FILL_TOLERANCE = 1e-3


class AnalysisError(Exception):
    """The captured data could not be analysed."""


@dataclass(frozen=True)
class Sweep:
    """An exponential sweep, as generated by the firmware `SweptSine` source.

    The firmware outputs `amplitude * sin(2π φ[n])` for `0 <= n < length` (and zero
    afterwards). `state` holds the instantaneous frequency in units of 2^-64
    cycles/sample and is multiplied by `1 + rate / 2^32` every sample, so that the phase
    in turns is approximately

        φ[n] = cycles * ((1 + rate / 2^32)^n - 1),   cycles = state / (2^32 rate).
    """

    #: Frequency growth rate (`Sweep::rate`).
    rate: int
    #: Initial frequency in units of 2^-64 cycles/sample (`Sweep::state`).
    state: int
    #: Number of samples.
    length: int
    #: Amplitude, in volts.
    amplitude: float
    #: Sample period, in seconds.
    sample_period: float

    @classmethod
    def design(cls, f_start: float, f_stop: float, duration: float, amplitude: float,
               sample_period: float) -> Sweep:
        """Find the firmware sweep parameters closest to the given ones.

        As the number of cycles per harmonic delay is rounded to an integer (at least
        one), the actual start frequency can differ from `f_start`; short sweeps cannot
        start at frequencies below about `ln(f_stop / f_start) / duration`. The length is
        then chosen to end the sweep at `f_stop`.
        """
        f1 = f_start * sample_period
        f2 = f_stop * sample_period
        if not 0 < f1 < f2:
            raise ValueError("Start frequency must be positive and below the stop "
                             "frequency")
        if f2 > MAX_STOP_FREQUENCY:
            raise ValueError("Stop frequency must be below "
                             f"{MAX_STOP_FREQUENCY / sample_period:.0f} Hz")
        if not 0 < abs(amplitude) < MAX_AMPLITUDE:
            raise ValueError(f"Amplitude must be between 0 and {MAX_AMPLITUDE} V")

        n = duration / sample_period
        if n < 1:
            raise ValueError("Duration too short")
        rate = round(_Q * math.expm1(math.log(f2 / f1) / n))
        if not 1 <= rate < (1 << 31):
            raise ValueError("Sweep rate out of range; adjust the duration")
        growth = math.log1p(rate / _Q)
        cycles = max(1, round(f1 / growth))
        f1 = cycles * growth
        if f1 >= f2:
            raise ValueError("Duration too short for the requested frequency range")
        length = round(math.log(f2 / f1) / growth)
        if length >= (1 << 32):
            raise ValueError("Sweep too long")
        return cls(rate, rate * cycles * _Q, length, float(amplitude), sample_period)

    @property
    def growth(self) -> float:
        """Exponential growth rate of the instantaneous frequency, per sample."""
        return math.log1p(self.rate / _Q)

    @property
    def cycles(self) -> float:
        """Number of cycles per harmonic delay (`f_start` times the e-folding time)."""
        return self.state / (_Q * self.rate)

    @property
    def f_start(self) -> float:
        return self.cycles * self.growth / self.sample_period

    @property
    def f_stop(self) -> float:
        return self.f_start * math.exp(self.growth * self.length)

    @property
    def duration(self) -> float:
        return self.length * self.sample_period

    def harmonic_delay(self, k: float) -> float:
        """Time by which the k-th harmonic of the sweep leads the fundamental, in samples.

        For an integer number of cycles, `sin(k φ[n]) = sin(φ[n + harmonic_delay(k)])`.
        """
        return math.log(k) / self.growth

    def phase(self) -> np.ndarray:
        """The phase of each sample, in turns.

        This follows the fixed-point arithmetic of the firmware, as the rounding errors
        accumulate to a noticeable phase error for long sweeps.
        """
        # `idsp::Sweep`: the frequency state for each sample.
        frequencies = array.array("q")
        append = frequencies.append
        state, rate = self.state, self.rate
        for _ in range(self.length):
            append(state)
            state += rate * ((state + (1 << 31)) >> 32)
        # `idsp::AccuOsc`: a wrapping 64-bit phase accumulator, of which the top 32 bits
        # are used.
        accumulator = np.zeros(self.length, np.uint64)
        np.cumsum(np.frombuffer(frequencies, np.int64)[:-1].view(np.uint64),
                  out=accumulator[1:])
        return (accumulator >> np.uint64(32)) / 2**32

    def excitation(self) -> np.ndarray:
        """The excitation added to the DAC output, in volts.

        This follows the firmware including the quantisation to DAC codes, which is
        significant for small amplitudes.
        """
        # `idsp::cossin` (approximated), scaled by `signal_generator::Scaler` (computed
        # in single precision), and truncated to the 16 bit DAC code.
        sine = np.clip(np.round(np.sin(2 * np.pi * self.phase()) * 2**31), -2**31,
                       2**31 - 1).astype(np.int64)
        scale = np.float32(self.amplitude) * (np.float32(1) / DAC_FULL_SCALE)
        amplitude = int(scale * np.float32(2**31))
        return ((sine * amplitude) >> 47) * DAC_VOLTS_PER_LSB

    def source_config(self) -> dict:
        """The settings of the firmware signal source (`ch/<n>/source/...`)."""
        return {
            "signal": "SweptSine",
            "amplitude": self.amplitude,
            "offset": 0.0,
            "length": self.length,
            "state": self.state,
            "rate": self.rate,
            # Unused for sweeps, but validated by the firmware for all signal types.
            "frequency": 1e3,
            "symmetry": 0.5,
            "phase": 0.0,
        }


@dataclass(frozen=True)
class AnalysisSettings:
    #: Length of the window applied to the linear impulse response, in seconds. This
    #: sets the frequency resolution (and thus the lowest usable frequency, and how
    #: sharp resonances can be resolved), but longer windows also collect more noise.
    ir_window: float
    #: Number of points per decade of the logarithmic frequency grid. The responses are
    #: averaged over the frequency interval each point represents, so this also sets the
    #: amount of smoothing.
    points_per_decade: int = 100
    #: Highest harmonic order for which the response is computed.
    max_harmonic: int = 4


def default_ir_window(sweep: Sweep) -> float:
    """Impulse response window covering ten periods of the start frequency."""
    return min(max(10 / sweep.f_start, 2e-3), 1.0)


def capture_tail(ir_window: float) -> float:
    """Time to keep capturing after the end of the sweep, in seconds.

    This covers the response to the end of the sweep and the window used for the
    noise estimate (which follows the impulse response window).
    """
    return 2.7 * ir_window + 0.02


@dataclass
class Analysis:
    """The results for each channel of the captured data. After the captured channels,
    the results include an additional channel: the reference channel with the
    excitation subtracted (for the DAC of the excited channel, the IIR filter output).
    """

    #: Frequencies of the results, in Hz.
    frequencies: np.ndarray
    #: Complex response of each channel relative to the stimulus, (n_channels, n_freq).
    responses: np.ndarray
    #: Estimated noise (1σ) of `responses`, or NaN if not available.
    noise: np.ndarray
    #: For each harmonic order k, the fundamental frequencies at which the harmonic
    #: responses are available, in Hz.
    harmonic_frequencies: dict[int, np.ndarray]
    #: For each harmonic order k, the complex response of each channel at k times the
    #: fundamental frequency, (n_channels, n_freq_k).
    harmonics: dict[int, np.ndarray]
    #: Estimated noise (1σ) of `harmonics`, or NaN if not available.
    harmonic_noise: dict[int, np.ndarray]
    #: Time axis of `impulse_responses`, relative to the start of the sweep.
    ir_time: np.ndarray
    #: Impulse responses (unwindowed) of each channel, (n_channels, n_time).
    impulse_responses: np.ndarray
    #: Window applied to the linear impulse response (start, stop), in s.
    ir_window: tuple[float, float]
    #: Window used for the noise estimate (start, stop), in s.
    noise_window: tuple[float, float] | None
    #: Windows used for the harmonics (start, stop), in s.
    harmonic_windows: dict[int, tuple[float, float]]
    #: Position of the start of the sweep in each run, in samples.
    offsets: list[int]
    warnings: list[str] = field(default_factory=list)

    @property
    def n_runs(self) -> int:
        return len(self.offsets)


def _band_window(f: np.ndarray, f1: float, f2: float) -> np.ndarray:
    """Band-pass window with raised-cosine edges (in log frequency)."""
    with np.errstate(divide="ignore"):
        log_f = np.log2(f)
    rise = np.clip((log_f - math.log2(f1)) / BAND_EDGE_TAPER, 0, 1)
    fall = np.clip((math.log2(f2) - log_f) / BAND_EDGE_TAPER, 0, 1)
    return np.sin(0.5 * np.pi * rise)**2 * np.sin(0.5 * np.pi * fall)**2


def _minimum_phase(magnitude: np.ndarray, n_fft: int, floor: float = 1e-6) -> np.ndarray:
    """Minimum phase spectrum with the given magnitude (sampled as by `rfft(·, n_fft)`),
    computed via the real cepstrum."""
    cepstrum = sfft.irfft(np.log(np.maximum(magnitude, floor)), n_fft)
    cepstrum[1:(n_fft + 1) // 2] *= 2
    cepstrum[n_fft // 2 + 1:] = 0
    return np.exp(sfft.rfft(cepstrum, n_fft))


class _Window:
    """Time window for an impulse response, rising over the `pre` samples before time
    zero, then flat for `length` samples, the last part of which are faded out."""

    def __init__(self, pre: int, length: int):
        self.pre = pre
        fade = max(1, int(_FADE_OUT * length))
        self.taper = np.concatenate([
            np.sin(0.5 * np.pi * (np.arange(pre) + 0.5) / pre)**2,
            np.ones(length - fade),
            np.cos(0.5 * np.pi * (np.arange(fade) + 0.5) / fade)**2,
        ])


def _segment(h: np.ndarray, start: int, length: int) -> np.ndarray:
    # The FFT length is chosen such that negative lags (e.g. the harmonics of a sweep
    # starting at the beginning of the record) wrap around without aliasing.
    return np.take(h, np.arange(start, start + length), mode="wrap")


def _grid_average(f: np.ndarray,
                  values: np.ndarray,
                  grid: np.ndarray,
                  points_per_decade: int,
                  rms: bool = False,
                  correlation: float = 1.0) -> np.ndarray:
    """Average `values` (sampled at the uniformly spaced `f`) over the frequency interval
    represented by each point of the logarithmic `grid`, interpolating where the interval
    is narrower than the spacing of `f`.

    With `rms`, `values` are taken to be noise samples, and the noise of their (complex)
    average is returned, for values correlated over `correlation` samples.
    """
    half_width = 10**(0.5 / points_per_decade)
    lo = np.searchsorted(f, grid / half_width)
    hi = np.searchsorted(f, grid * half_width)
    averaged = hi > lo
    counts = (hi - lo)[averaged]
    # The values in each interval, concatenated, and the intervals' bounds in this list.
    starts = np.cumsum(counts) - counts
    ends = starts + counts
    index = np.arange(np.sum(counts)) + np.repeat(lo[averaged] - starts, counts)

    def interval_sum(x, start, end):
        cumulative = np.concatenate([[0], np.cumsum(x)])
        return cumulative[end] - cumulative[start]

    if rms:
        result = np.interp(grid, f, np.abs(values))
        power = interval_sum(np.abs(values[index])**2, starts, ends) / counts
        result[averaged] = np.sqrt(power * np.minimum(1, correlation / counts))
        return result

    result = np.interp(grid, f, values.real) + 1j * np.interp(grid, f, values.imag)
    if not len(counts):
        return result
    # The phase can change considerably over the interval (due to delays), which would
    # bias a complex average. Thus, estimate the local group delay from the change in
    # phase (relative to the value at the centre, to avoid wrapping) between the lower
    # and upper half of each interval, and compensate for it in the average. (Averaging
    # magnitude and phase separately instead would be biased by noise.)
    centre = result[averaged]
    v, fv = values[index], f[index]
    relative_phase = np.angle(v * np.repeat(np.conj(centre), counts))
    middles = starts + counts // 2
    lower, upper = middles - starts, ends - middles
    with np.errstate(invalid="ignore", divide="ignore"):
        slope = ((interval_sum(relative_phase, middles, ends) / upper -
                  interval_sum(relative_phase, starts, middles) / lower) /
                 (interval_sum(fv, middles, ends) / upper -
                  interval_sum(fv, starts, middles) / lower))
    slope = np.where(lower > 0, slope, 0)
    rotation = np.exp(-1j * np.repeat(slope, counts) *
                      (fv - np.repeat(grid[averaged], counts)))
    result[averaged] = interval_sum(v * rotation, starts, ends) / counts
    return result


class _Deconvolver:
    """Deconvolves records of a given length with the sweep."""

    def __init__(self, sweep: Sweep, excitation: np.ndarray, record_length: int):
        self.n_fft = sfft.next_fast_len(record_length + sweep.length, real=True)
        # Normalise the impulse responses to the (nominal) amplitude.
        self.amplitude = sweep.amplitude
        spectrum = sfft.rfft(excitation / self.amplitude, self.n_fft)
        f = np.arange(len(spectrum)) / self.n_fft
        f1 = sweep.f_start * sweep.sample_period
        f2 = sweep.f_stop * sweep.sample_period
        # Limit the band with a minimum phase filter, as the long and acausal components
        # of a zero phase one would be cut off by the time windows.
        band = _minimum_phase(_band_window(f, f1, f2), self.n_fft)
        # Expected power spectral density of the sweep (stationary phase approximation).
        expected = np.empty_like(f)
        expected[1:] = 1 / (4 * sweep.growth * f[1:])
        expected[0] = expected[1]
        power = np.abs(spectrum)**2
        self.inverse = band * np.conj(spectrum) / (power + _REGULARISATION * expected)
        #: The (band-limited) impulse response obtained for a unity-gain system.
        self.unity = sfft.irfft(self.inverse * spectrum, self.n_fft)
        #: Position of the peak of `unity`.
        self.peak_delay = int(np.argmax(np.abs(self.unity[:self.n_fft // 2])))
        #: Frequencies (cycles/sample) of the spectra of records (`rfft(·, n_fft)`).
        self.frequencies = f

    def __call__(self, record: np.ndarray, start: int | None = None) -> np.ndarray:
        """Deconvolve `record`, in which the sweep starts at `start` (if known).

        Steps at the ends of the record would show up in the impulse response, so the
        record is taken relative to the level before the sweep, and faded in and out.
        """
        if start is None:
            record = record - np.mean(record)
        else:
            record = record - np.mean(record[:max(start, 1)])
            fade = min(start // 2, len(record) // 100)
            if fade > 0:
                ramp = np.sin(0.5 * np.pi * (np.arange(fade) + 0.5) / fade)**2
                record[:fade] *= ramp
                record[-fade:] *= ramp[::-1]
        return self.deconvolve(record)

    def deconvolve(self, record: np.ndarray) -> np.ndarray:
        """Deconvolve `record` as is."""
        return sfft.irfft(
            sfft.rfft(record / self.amplitude, self.n_fft) * self.inverse, self.n_fft)


def _interpolate_gaps(x: np.ndarray, gaps: np.ndarray) -> np.ndarray:
    """`x` with the sample ranges `gaps` (start, stop) interpolated linearly from the
    neighbouring samples (as `Measurement.volts()` does for lost data)."""
    if not len(gaps):
        return x
    mask = np.zeros(len(x), bool)
    for start, stop in gaps:
        mask[start:stop] = True
    index = np.arange(len(x))
    x = x.copy()
    x[mask] = np.interp(index[mask], index[~mask], x[~mask])
    return x


def find_sweep_start(h_reference: np.ndarray, record_length: int, unity: np.ndarray,
                     peak_delay: int, batch_size: int, warnings: list[str]) -> int:
    """Locate the start of the sweep in the impulse response `h_reference` of a channel
    which contains the stimulus directly (the DAC output of the excited channel), given
    the impulse response `unity` of a unity-gain system, which peaks at `peak_delay`."""
    magnitude = np.abs(h_reference[:record_length])
    peak = int(np.argmax(magnitude))
    if magnitude[peak] < 0.1 * abs(unity[peak_delay]):
        raise AnalysisError("Sweep not found in the captured data")
    offset = peak - peak_delay

    # The source is updated at batch boundaries, and captures start at one.
    aligned = int(round(offset / batch_size)) * batch_size
    if aligned != offset:
        if abs(aligned - offset) <= 2:
            warnings.append(f"Sweep start found {offset - aligned} samples off the "
                            "batch boundary; using the boundary")
            offset = aligned
        else:
            warnings.append("Sweep start not aligned to batch boundary "
                            f"(offset {offset} samples)")
    return offset


def _affected(f: np.ndarray, gaps: np.ndarray, lag_start: int, lag_stop: int,
              sweep: Sweep) -> np.ndarray:
    """Which of the frequencies `f` (cycles/sample) read from a window of the impulse
    response at lags `lag_start` to `lag_stop` (relative to the sweep start) receive the
    record at the sample ranges `gaps` (start, stop; relative to the sweep start).

    The deconvolution places the record at time t and frequency f at the lag t - t_f,
    where t_f is the time at which the sweep passes f (the inverse filter is essentially
    the time-reversed sweep).
    """
    f1 = sweep.f_start * sweep.sample_period
    margin = 2**_GAP_MARGIN
    affected = np.zeros(len(f), bool)
    for start, stop in gaps:
        low = f1 * math.exp(sweep.growth * (start - lag_stop)) / margin
        high = f1 * math.exp(sweep.growth * (stop - lag_start)) * margin
        affected |= (f >= low) & (f <= high)
    return affected


def _format_frequency(f: float) -> str:
    return f"{f / 1e3:.3g} kHz" if f >= 1e3 else f"{f:.3g} Hz"


def analyse(runs: list[np.ndarray],
            sweep: Sweep,
            reference: int,
            batch_size: int,
            settings: AnalysisSettings,
            offsets: list[int] | None = None,
            gaps: list[np.ndarray] | None = None) -> Analysis:
    """Estimate the responses of all channels to the sweep, averaged over several runs.

    :param runs: For each run, the captured data of all channels, (n_channels, length),
        in volts.
    :param reference: Index of the channel containing the stimulus directly (the DAC
        output of the excited channel), used to locate the sweep start.
    :param batch_size: The stream batch size; the sweep starts at a batch boundary.
    :param offsets: The start of the sweep in each run, if already known.
    :param gaps: For each run, the ranges of samples (start, stop) which were lost and
        have been interpolated linearly, as an (n, 2) array. The response to the
        stimulus lost during the sweep is filled in from the estimated response, and the
        noise estimate of the run is left out at the frequencies affected by what
        remains (see `fill_gaps()` in the code).
    """
    warnings = []
    sample_period = sweep.sample_period
    f1 = sweep.f_start * sample_period
    f2 = sweep.f_stop * sample_period

    # Window parameters (in samples). The windows rise smoothly over `pre` samples before
    # time zero of the respective impulse response: sharp edges would mix the response
    # near the band edges into the whole band. They are limited by the spacing to the
    # (earlier) impulse response of the next higher harmonic.
    n_window = max(16, int(round(settings.ir_window / sample_period)))
    pre = int(np.clip(0.4 * sweep.harmonic_delay(2), 32, n_window // 2))
    window = _Window(pre, n_window)

    harmonic_windows = {}
    end = -pre  # End of the following window.
    for k in range(2, settings.max_harmonic + 1):
        delay = sweep.harmonic_delay(k)
        harmonic_pre = int(0.3 * (sweep.harmonic_delay(k + 1) - delay))
        length = int(end + delay)
        if harmonic_pre < 4 or length < 16 or k * f1 >= f2:
            break
        harmonic_windows[k] = _Window(harmonic_pre, length)
        end = int(-delay) - harmonic_pre
    harmonic_orders = list(harmonic_windows)

    n_spectrum = sfft.next_fast_len(
        2 * max(len(w.taper) for w in [window, *harmonic_windows.values()]), real=True)
    f_spectrum = np.arange(n_spectrum // 2 + 1) / n_spectrum

    # Logarithmic frequency grid inside the analysis band.
    f_lo = f1 * 2**BAND_EDGE_TAPER
    f_hi = f2 * 2**-BAND_EDGE_TAPER
    if f_lo >= f_hi:
        raise AnalysisError("Frequency range too narrow")
    n_grid = max(2, math.ceil(math.log10(f_hi / f_lo) * settings.points_per_decade) + 1)
    grid = np.geomspace(f_lo, f_hi, n_grid)
    # The harmonics only cover output frequencies from k times the start frequency,
    # leading to an additional band edge there.
    harmonic_grids = {
        k: grid[(k * grid <= f_hi) & (grid >= f_lo * 2**(2 * BAND_EDGE_TAPER))]
        for k in harmonic_orders
    }

    # The noise is estimated from the impulse response following the response window
    # (with the window shape of the respective response), starting here.
    noise_start = n_window - pre

    # Section of the impulse responses to keep for display.
    ir_start = min(-pre, end)
    ir_stop = noise_start + max(
        len(w.taper) for w in [window, *harmonic_windows.values()])

    def spectrum(segment, shift):
        """Spectrum of an impulse response segment, with time zero `shift` samples into
        the segment."""
        return sfft.rfft(segment, n_spectrum) * np.exp(2j * np.pi * f_spectrum * shift)

    def response(h, deconvolve, start, window, frequencies, fraction=0.0, noise=()):
        """Response at `frequencies` (cycles/sample) from the impulse response `h`
        with time zero at `start + fraction`.

        The band limits of the deconvolution lead to long components in the impulse
        responses, which are cut off by the time window, and thus to errors near the band
        edges. To correct for this, the result is normalised by the same windowing of
        the impulse response of a unity-gain system with the same bulk delay
        ("normalised convolution"). This is accurate as long as the response is smooth
        on the scale of the frequency resolution.

        `noise` is a list of (window, frequencies), for which to estimate the noise from
        the impulse response following `window`, as for the response itself (e.g. the
        same `window` and `frequencies`, or those of the harmonics).

        Returns the response, the noise estimates, and the bulk delay found (in samples).
        """
        taper = window.taper
        segment = _segment(h, start - window.pre, len(taper)) * taper
        # The bulk delay of the response, beyond that of the band limiting filter.
        delay = int(np.argmax(np.abs(segment[window.pre:]))) - deconvolve.peak_delay
        reference = _segment(deconvolve.unity, -window.pre - delay, len(taper)) * taper
        # Remove the bulk delay before averaging over frequency (and restore it after).
        shift = window.pre + delay
        values = spectrum(segment, shift)
        unity_values = spectrum(reference, shift)
        average = partial(_grid_average,
                          grid=frequencies,
                          points_per_decade=settings.points_per_decade)
        unity_average = average(f_spectrum, unity_values)
        result = (average(f_spectrum, values) / unity_average *
                  np.exp(-2j * np.pi * frequencies * (delay - fraction)))
        if not noise:
            return result, [], delay

        # The following part of the impulse response contains the noise, as well as the
        # continuation of the band limiting filter response, which is subtracted using
        # the response estimate.
        with np.errstate(invalid="ignore", divide="ignore"):
            estimate = values / unity_values
        estimate = np.where(np.isfinite(estimate), estimate, 0)
        estimates = []
        for noise_window, noise_frequencies in noise:
            noise_taper = noise_window.taper
            noise_values = spectrum(
                _segment(h, start + noise_start, len(noise_taper)) * noise_taper, shift)
            continuation = spectrum(
                _segment(deconvolve.unity, noise_start - delay, len(noise_taper)) *
                noise_taper, shift)
            noise_values -= estimate * continuation
            # The estimate carries the noise of the response window (relative to the
            # windowed unity response), which the subtraction adds to that of the noise
            # window. This matters where the continuation is not small against the
            # windowed unity response, i.e. near the band edges (where the band limiting
            # filter rings for long); take the added noise out of the power.
            with np.errstate(invalid="ignore", divide="ignore"):
                added = np.abs(continuation / unity_values)**2
            noise_values /= np.sqrt(1 + np.where(np.isfinite(added), added, 0))
            # Averaging over a frequency interval Δf selects a time span of about 1 / Δf
            # of the window; the zero-padded spectrum samples are correlated accordingly.
            correlation = n_spectrum / np.sum(noise_taper**2)
            noise_average = _grid_average(f_spectrum, noise_values, noise_frequencies,
                                          settings.points_per_decade, True, correlation)
            # Relative to the gain of the window, as for the response.
            gain = _grid_average(
                f_spectrum,
                spectrum(
                    _segment(deconvolve.unity, -noise_window.pre - delay,
                             len(noise_taper)) * noise_taper, noise_window.pre + delay),
                noise_frequencies, settings.points_per_decade)
            estimates.append(noise_average / np.abs(gain))
        return result, estimates, delay

    def fill_gaps(h, record, deconvolve, offset, gaps, stimulus_spectrum):
        """Correct the impulse response `h` of `record` for its lost samples (the ranges
        `gaps`), which have been interpolated linearly.

        The interpolation replaces the response to the stimulus there by a straight
        line. What it removes is a burst, which the deconvolution spreads along a chirp
        (the time-reversed sweep) through the impulse response, where it swamps the
        harmonics and the noise estimate at the frequencies at which the chirp passes
        their windows, and biases the response at the frequency of the sweep at that
        time. The linear response of the channel to the stimulus is known from the
        estimate of its response (and the stimulus exactly), so this models what the
        interpolation removed, and adds its impulse response back. As the estimate is
        itself biased by what is missing, this is repeated with the corrected impulse
        response.
        """
        f = deconvolve.frequencies
        with np.errstate(divide="ignore"):
            log_f = np.log(f)
        log_grid = np.log(grid)
        corrected = h
        previous = None
        for _ in range(_GAP_FILL_PASSES):
            result, _, delay = response(corrected, deconvolve, offset, window, grid)
            # The response at the frequencies of the record spectrum: interpolate the
            # smooth part (without the bulk delay) on the logarithmic grid.
            smooth = result * np.exp(2j * np.pi * grid * delay)
            estimate = (np.interp(log_f, log_grid, smooth.real) +
                        1j * np.interp(log_f, log_grid, smooth.imag))
            estimate *= np.exp(-2j * np.pi * f * delay)
            model = sfft.irfft(stimulus_spectrum * estimate,
                               deconvolve.n_fft)[:len(record)]
            fill = model - _interpolate_gaps(model, gaps)
            corrected = h + deconvolve.deconvolve(fill)
            if previous is not None and (np.max(np.abs(fill - previous))
                                         <= _GAP_FILL_TOLERANCE * np.max(np.abs(fill))):
                break
            previous = fill
        return corrected

    # Additionally analyse the reference channel with the excitation subtracted.
    n_channels = runs[0].shape[0] + 1
    responses = np.zeros((len(runs), n_channels, n_grid), complex)
    noise = np.full((len(runs), n_channels, n_grid), np.nan)
    harmonics = {
        k: np.zeros((len(runs), n_channels, len(g)), complex)
        for k, g in harmonic_grids.items()
    }
    harmonic_noise = {k: np.full(v.shape, np.nan) for k, v in harmonics.items()}
    impulse_responses = np.zeros((n_channels, ir_stop - ir_start))
    found_offsets = []
    noise_available = True
    #: Frequencies of the sweep at the times of lost data.
    gap_frequencies = []

    excitation = sweep.excitation()
    deconvolvers = {}
    for run, records in enumerate(runs):
        record_length = records.shape[1]
        # Keep the most recent deconvolver, as the runs usually have the same length.
        if record_length not in deconvolvers:
            deconvolvers = {record_length: _Deconvolver(sweep, excitation, record_length)}
        deconvolve = deconvolvers[record_length]
        if offsets is None:
            offset = find_sweep_start(deconvolve(records[reference]), record_length,
                                      deconvolve.unity, deconvolve.peak_delay, batch_size,
                                      warnings)
        else:
            offset = offsets[run]
        found_offsets.append(offset)

        after_sweep = record_length - (offset + sweep.length)
        if after_sweep < 0:
            raise AnalysisError("The sweep was not captured completely")
        if after_sweep < n_window:
            warnings.append("Capture ended before the end of the impulse response "
                            "window")
        # The noise windows collect the noise from the following sweep length of the
        # record.
        noise_windows = [(window, grid)] + [(harmonic_windows[k], k * harmonic_grids[k])
                                            for k in harmonic_orders]
        has_noise = [
            offset + noise_start + len(w.taper) + sweep.length <= record_length
            for w, _ in noise_windows
        ]
        noise_available &= has_noise[0]
        # Lost (interpolated) data during the sweep (see `gaps` above), relative to
        # the start of the sweep.
        run_gaps = np.zeros((0, 2), int)
        if gaps is not None and len(gaps[run]):
            run_gaps = np.clip(
                np.asarray(gaps[run], int).reshape(-1, 2) - offset, 0, sweep.length)
            run_gaps = run_gaps[run_gaps[:, 1] > run_gaps[:, 0]]
        for gap_start, gap_stop in run_gaps:
            gap_frequencies.append(sweep.f_start * math.exp(sweep.growth *
                                                            (gap_start + gap_stop) / 2))
        # The noise estimate is left out where the window receives what remains of
        # the lost data (see `fill_gaps()`).
        noise_affected = [
            _affected(frequencies, run_gaps, noise_start, noise_start + len(w.taper),
                      sweep) for w, frequencies in noise_windows
        ]

        stimulus = np.zeros(record_length)
        stimulus[offset:offset + sweep.length] = excitation
        stimulus_spectrum = None
        if len(run_gaps):
            stimulus_spectrum = sfft.rfft(stimulus, deconvolve.n_fft)
            # Interpolated like the record, so that the difference is the interpolated
            # filter output.
            stimulus = _interpolate_gaps(stimulus, run_gaps + offset)
        reference_output = records[reference] - stimulus
        for channel, record in enumerate([*records, reference_output]):
            h = deconvolve(record, offset)
            if len(run_gaps):
                h = fill_gaps(h, record, deconvolve, offset, run_gaps + offset,
                              stimulus_spectrum)
            result, noise_estimates, _ = response(h,
                                                  deconvolve,
                                                  offset,
                                                  window,
                                                  grid,
                                                  noise=noise_windows)
            responses[run, channel] = result
            for i, estimate in enumerate(noise_estimates):
                if has_noise[i]:
                    estimate[noise_affected[i]] = np.nan
                    if i == 0:
                        noise[run, channel] = estimate
                    else:
                        harmonic_noise[harmonic_orders[i - 1]][run, channel] = estimate
            for k in harmonic_orders:
                delay = sweep.harmonic_delay(k)
                result, _, _ = response(h, deconvolve, offset - round(delay),
                                        harmonic_windows[k], k * harmonic_grids[k],
                                        round(delay) - delay)
                harmonics[k][run, channel] = result
            impulse_responses[channel] += _segment(h, offset + ir_start,
                                                   ir_stop - ir_start)

    if not noise_available:
        warnings.append("Capture too short for a noise estimate")
    if gap_frequencies:
        gap_frequencies.sort()
        if len(gap_frequencies) == 1:
            where = f"at {_format_frequency(gap_frequencies[0])}"
        elif len(gap_frequencies) <= 3:
            where = "at " + ", ".join(map(_format_frequency, gap_frequencies))
        else:
            where = (f"{len(gap_frequencies)} times between "
                     f"{_format_frequency(gap_frequencies[0])} and "
                     f"{_format_frequency(gap_frequencies[-1])}")
        warnings.append(f"Stream data lost during the sweep {where} (filled in from "
                        "the response; left out of the noise estimate)")

    n_runs = len(runs)

    def noise_of_average(per_run):
        """The noise of the average of the independent runs, from the runs with an
        estimate (NaN where there is none)."""
        valid = np.isfinite(per_run)
        with np.errstate(invalid="ignore", divide="ignore"):
            return np.sqrt(
                np.sum(np.where(valid, per_run, 0)**2, axis=0) / np.sum(valid, axis=0) /
                n_runs)

    return Analysis(
        frequencies=grid / sample_period,
        responses=np.mean(responses, axis=0),
        noise=noise_of_average(noise),
        harmonic_frequencies={
            k: g / sample_period
            for k, g in harmonic_grids.items()
        },
        harmonics={
            k: np.mean(v, axis=0)
            for k, v in harmonics.items()
        },
        harmonic_noise={
            k: noise_of_average(v)
            for k, v in harmonic_noise.items()
        },
        ir_time=np.arange(ir_start, ir_stop) * sample_period,
        impulse_responses=impulse_responses / n_runs,
        ir_window=(-pre * sample_period, n_window * sample_period),
        noise_window=(noise_start * sample_period, (noise_start + len(window.taper)) *
                      sample_period) if noise_available else None,
        harmonic_windows={
            k: ((-sweep.harmonic_delay(k) - w.pre) * sample_period,
                (-sweep.harmonic_delay(k) + len(w.taper) - w.pre) * sample_period)
            for k, w in harmonic_windows.items()
        },
        offsets=found_offsets,
        warnings=list(dict.fromkeys(warnings)),
    )


#: Quantities derived from the responses, relative to the excited channel `n`.
#: The firmware adds the stimulus `s` to the output `y` of the IIR filter `C`, so that
#: `DAC = y + s = C ADC + s`. With the plant `P` (from DAC to ADC of the same channel),
#: the (negative feedback) loop gain is `L = -C P`, and `DAC / s = 1 / (1 + L)`.
QUANTITIES = {
    "plant": "Plant P = ADC{n} / DAC{n}",
    "loop": "Loop gain L = −CP = −y / DAC{n}",
    "controller": "Controller C = y / ADC{n}",
    "sensitivity": "Sensitivity 1 / (1 + L) = DAC{n} / s",
    "complementary": "Complementary sensitivity L / (1 + L) = −y / s",
    "adc": "ADC{n} / s",
    "adc_other": "ADC{m} / s (other channel)",
    "dac_other": "DAC{m} / s (other channel)",
}


def filter_output_name(n: int) -> str:
    """Name of the filter output `y` (the DAC output without the stimulus) of channel `n`
    in the `responses` passed to `derived_quantity()`."""
    return f"Y{n}"


def derived_quantity(quantity: str, responses: dict, noise: dict,
                     n: int) -> tuple[np.ndarray, np.ndarray]:
    """Compute one of `QUANTITIES` and its (first-order) noise estimate.

    :param responses: The response to the stimulus `s` of each channel (complex arrays),
        by channel name (`ADC0`, `DAC1`, …, and the filter output `y`, see
        `filter_output_name()`).
    :param noise: The noise estimates of `responses`, by channel name.
    :param n: The excited channel.
    """
    m = 1 - n
    adc, adc_noise = responses[f"ADC{n}"], noise[f"ADC{n}"]
    dac, dac_noise = responses[f"DAC{n}"], noise[f"DAC{n}"]
    y, y_noise = responses[filter_output_name(n)], noise[filter_output_name(n)]

    def ratio(a, a_noise, b, b_noise):
        value = a / b
        return value, np.abs(value) * np.hypot(a_noise / np.abs(a), b_noise / np.abs(b))

    with np.errstate(divide="ignore", invalid="ignore"):
        if quantity == "plant":
            return ratio(adc, adc_noise, dac, dac_noise)
        if quantity == "loop":
            return ratio(-y, y_noise, dac, dac_noise)
        if quantity == "controller":
            return ratio(y, y_noise, adc, adc_noise)
        if quantity == "sensitivity":
            return dac, dac_noise
        if quantity == "complementary":
            return -y, y_noise
        if quantity == "adc":
            return adc, adc_noise
        if quantity == "adc_other":
            return responses[f"ADC{m}"], noise[f"ADC{m}"]
        if quantity == "dac_other":
            return responses[f"DAC{m}"], noise[f"DAC{m}"]
    raise ValueError(f"Unknown quantity '{quantity}'")


def quantity_label(quantity: str, n: int) -> str:
    return QUANTITIES[quantity].format(n=n, m=1 - n)


#: For each of the `QUANTITIES`, the channel whose harmonics are shown, and the channel
#: whose (fundamental) response they are normalised to (None for the stimulus).
HARMONIC_CHANNELS = {
    "plant": ("ADC{n}", "DAC{n}"),
    "loop": ("Y{n}", "DAC{n}"),
    "controller": ("Y{n}", "ADC{n}"),
    "sensitivity": ("DAC{n}", None),
    "complementary": ("Y{n}", None),
    "adc": ("ADC{n}", None),
    "adc_other": ("ADC{m}", None),
    "dac_other": ("DAC{m}", None),
}


def derived_harmonic(quantity: str, harmonics: dict, harmonic_noise: dict,
                     responses: dict, frequencies: np.ndarray,
                     harmonic_frequencies: np.ndarray,
                     n: int) -> tuple[np.ndarray, np.ndarray]:
    """The harmonic response corresponding to one of `QUANTITIES`, and its noise.

    This is the harmonic response of the output channel of the quantity (at k times the
    fundamental frequency), normalised like the quantity, e.g. for the plant, the ADC
    harmonic relative to the DAC fundamental. Its ratio to the quantity is thus the
    harmonic distortion of that channel. (Only the magnitude is meaningful.)

    :param harmonics: The k-th harmonic response of each channel, by channel name.
    :param harmonic_noise: The noise estimates of `harmonics`.
    :param responses: The (fundamental) responses of each channel, at `frequencies`.
    :param harmonic_frequencies: The fundamental frequencies of `harmonics`.
    """
    output, reference = (None if name is None else name.format(n=n, m=1 - n)
                         for name in HARMONIC_CHANNELS[quantity])
    value, noise = harmonics[output], harmonic_noise[output]
    if reference is not None:
        log_f = np.log(harmonic_frequencies)
        response = responses[reference]
        reference = (np.interp(log_f, np.log(frequencies), response.real) +
                     1j * np.interp(log_f, np.log(frequencies), response.imag))
        with np.errstate(divide="ignore", invalid="ignore"):
            value, noise = value / reference, noise / np.abs(reference)
    return value, noise
