//! Transfer function estimation from exponential sine sweeps (ESS).
//!
//! The excitation is generated on the device by the `SweptSine` signal source of the
//! `dual-iir` firmware, which is added to the DAC output of a channel. As the stimulus
//! is known exactly, the responses of all streamed channels can be deconvolved with it
//! (Farina's method). In the resulting impulse responses, the harmonic distortion
//! products appear before the linear response, so that they can be separated by
//! windowing. With an integer number of cycles per harmonic delay ("synchronized" swept
//! sine, Novák et al., JAES 63, 786 (2015)), the harmonic impulse responses have a
//! well-defined phase.
//!
//! `analyse()` is called from `stabilizer_ui.transfer_function.ess.analyse()`, which
//! documents the parameters and results. Frequencies are in cycles/sample and times in
//! samples throughout. The channels (and runs) are analysed in parallel, as many at a
//! time as fit a memory budget, with the large arrays of each reused between the steps.

use std::collections::{BTreeMap, HashMap};
use std::f64::consts::PI;
use std::sync::{Arc, Mutex};

use idsp::AccuOsc;
use num_complex::Complex64 as C64;
use rayon::prelude::*;
use realfft::{ComplexToReal, RealFftPlanner, RealToComplex};

/// DAC full scale, in volts, as the firmware computes it (single precision).
const DAC_FULL_SCALE: f32 = 4.096 * 2.5;
/// Width of the raised-cosine tapers at either end of the analysis band, in octaves.
const BAND_EDGE_TAPER: f64 = 1.0 / 12.0;
/// Regularisation of the inverse filter, relative to the expected sweep PSD.
const REGULARISATION: f64 = 1e-4;
/// Magnitude floor of the minimum phase band limiting filter.
const MIN_PHASE_FLOOR: f64 = 1e-6;
/// Fraction of the impulse response window over which it is faded out.
const FADE_OUT: f64 = 0.25;
/// Margin, in octaves, around the frequencies affected by lost data.
const GAP_MARGIN: f64 = 1.0 / 24.0;
/// Passes of filling in lost data, and the relative change at which to stop.
const GAP_FILL_PASSES: usize = 8;
const GAP_FILL_TOLERANCE: f64 = 1e-3;

/// An exponential sweep, as generated by the firmware `SweptSine` source.
#[derive(Clone, Debug)]
pub struct Sweep {
    /// The firmware's oscillator parameters: the rate and the initial frequency state.
    pub source: idsp::Sweep,
    pub length: usize,
    /// Amplitude, in volts.
    pub amplitude: f64,
    /// Sample period, in seconds.
    pub sample_period: f64,
}

impl Sweep {
    pub fn new(rate: i32, state: i64, length: usize, amplitude: f64, sample_period: f64) -> Self {
        Self {
            source: idsp::Sweep::new(rate, state),
            length,
            amplitude,
            sample_period,
        }
    }

    /// Exponential growth rate of the instantaneous frequency, per sample.
    pub fn growth(&self) -> f64 {
        self.source.rate()
    }

    /// Start frequency, in cycles/sample.
    pub fn f_start(&self) -> f64 {
        self.source.state()
    }

    /// Stop frequency, in cycles/sample.
    pub fn f_stop(&self) -> f64 {
        self.f_start() * (self.growth() * self.length as f64).exp()
    }

    /// Time by which the k-th harmonic leads the fundamental, in samples.
    pub fn harmonic_delay(&self, k: f64) -> f64 {
        self.source.delay(k)
    }

    /// The excitation added to the DAC output, in volts, exactly as the firmware
    /// generates it: `idsp::AccuOsc` over `idsp::Sweep` (with its table-based sine),
    /// scaled by `signal_generator::Scaler` (computed in single precision) and
    /// truncated to the 16-bit DAC code.
    pub fn excitation(&self) -> Vec<f64> {
        let amplitude = (self.amplitude as f32 * DAC_FULL_SCALE.recip() * 2147483648f32) as i64;
        let volts_per_lsb = DAC_FULL_SCALE as f64 / 32768.0;
        AccuOsc::new(self.source.clone())
            .take(self.length)
            .map(|c| ((((c.im() as i64 * amplitude) >> 31) as i32) >> 16) as f64 * volts_per_lsb)
            .collect()
    }
}

#[derive(Clone, Copy, Debug)]
pub struct Settings {
    /// Length of the impulse response window, in seconds.
    pub ir_window: f64,
    pub points_per_decade: u32,
    pub max_harmonic: u32,
    /// Memory budget for the buffers of the channels analysed in parallel, in bytes.
    pub memory: usize,
}

/// The results, with frequencies in cycles/sample and times in samples.
#[derive(Debug, Default)]
pub struct Analysis {
    pub frequencies: Vec<f64>,
    /// (n_channels, n_frequencies)
    pub responses: Vec<Vec<C64>>,
    pub noise: Vec<Vec<f64>>,
    pub harmonic_orders: Vec<usize>,
    pub harmonic_frequencies: Vec<Vec<f64>>,
    /// Per order, (n_channels, n_frequencies).
    pub harmonics: Vec<Vec<Vec<C64>>>,
    pub harmonic_noise: Vec<Vec<Vec<f64>>>,
    /// Time of the first sample of `impulse_responses`, relative to the sweep start.
    pub ir_start: i64,
    pub impulse_responses: Vec<Vec<f64>>,
    pub ir_window: (i64, i64),
    pub noise_window: Option<(i64, i64)>,
    pub harmonic_windows: Vec<(f64, f64)>,
    pub offsets: Vec<i64>,
    /// The frequency of the sweep at each gap of lost data during it, over all runs.
    pub gap_frequencies: Vec<f64>,
    pub warnings: Vec<String>,
}

/// A length `>= n` for which the FFTs are fast: rustfft is fastest for powers of two,
/// and nearly as fast with one factor of 3 (less so with 9, 5 or 15), so a longer
/// transform can be the quicker one.
pub fn fast_length(n: usize) -> usize {
    const FORMS: [(usize, f64); 5] = [(1, 1.0), (3, 1.05), (9, 1.2), (5, 1.2), (15, 1.5)];
    FORMS
        .iter()
        .map(|&(m, cost)| {
            let mut length = m;
            while length < n {
                length *= 2;
            }
            (length, length as f64 * cost)
        })
        .min_by(|a, b| a.1.total_cmp(&b.1))
        .unwrap()
        .0
}

/// Real FFTs of one length (`scipy.fft.rfft`/`irfft` conventions).
#[derive(Clone)]
struct Fft {
    n: usize,
    forward: Arc<dyn RealToComplex<f64>>,
    inverse: Arc<dyn ComplexToReal<f64>>,
}

impl Fft {
    fn new(n: usize) -> Self {
        let mut planner = RealFftPlanner::new();
        Self {
            n,
            forward: planner.plan_fft_forward(n),
            inverse: planner.plan_fft_inverse(n),
        }
    }

    fn bins(&self) -> usize {
        self.n / 2 + 1
    }

    /// Forward transform (`input` is used as scratch space).
    fn forward(&self, input: &mut [f64], output: &mut [C64]) {
        self.forward.process(input, output).unwrap();
    }

    /// Inverse transform, normalised by `1 / n` (`input` is used as scratch space; the
    /// imaginary parts of the DC and Nyquist bins are ignored).
    fn inverse(&self, input: &mut [C64], output: &mut [f64]) {
        input[0].im = 0.0;
        if self.n.is_multiple_of(2) {
            input[self.n / 2].im = 0.0;
        }
        self.inverse.process(input, output).unwrap();
        let scale = 1.0 / self.n as f64;
        output.iter_mut().for_each(|x| *x *= scale);
    }
}

/// Index of the first element of the largest magnitude (`max_by` returns the last of
/// equal elements, hence the reversed range).
fn argmax_abs(x: &[f64]) -> usize {
    (0..x.len())
        .rev()
        .max_by(|&i, &j| x[i].abs().total_cmp(&x[j].abs()))
        .unwrap_or(0)
}

fn raised_cosine(i: usize, n: usize) -> f64 {
    (0.5 * std::f64::consts::PI * (i as f64 + 0.5) / n as f64)
        .sin()
        .powi(2)
}

/// Copy `length` samples of `src` from `start` into `dst`, wrapping around.
fn take_wrapped(src: &[f64], start: i64, dst: &mut [f64]) {
    let n = src.len();
    let mut i = start.rem_euclid(n as i64) as usize;
    let mut remaining = dst;
    while !remaining.is_empty() {
        let count = remaining.len().min(n - i);
        let (head, tail) = remaining.split_at_mut(count);
        head.copy_from_slice(&src[i..i + count]);
        remaining = tail;
        i = (i + count) % n;
    }
}

/// Band-pass window with raised-cosine edges (in log frequency).
fn band_window(f: f64, f1: f64, f2: f64) -> f64 {
    let log_f = f.log2();
    let rise = ((log_f - f1.log2()) / BAND_EDGE_TAPER).clamp(0.0, 1.0);
    let fall = ((f2.log2() - log_f) / BAND_EDGE_TAPER).clamp(0.0, 1.0);
    let half_pi = 0.5 * std::f64::consts::PI;
    (half_pi * rise).sin().powi(2) * (half_pi * fall).sin().powi(2)
}

/// Minimum phase spectrum with the given magnitude, via the real cepstrum.
fn minimum_phase(fft: &Fft, magnitude: &[f64]) -> Vec<C64> {
    let n = fft.n;
    let mut spectrum: Vec<C64> = magnitude
        .par_iter()
        .map(|&m| C64::new(m.max(MIN_PHASE_FLOOR).ln(), 0.0))
        .collect();
    let mut cepstrum = vec![0.0; n];
    fft.inverse(&mut spectrum, &mut cepstrum);
    cepstrum[1..n.div_ceil(2)]
        .iter_mut()
        .for_each(|x| *x *= 2.0);
    cepstrum[n / 2 + 1..].fill(0.0);
    fft.forward(&mut cepstrum, &mut spectrum);
    spectrum.par_iter_mut().for_each(|z| *z = z.exp());
    spectrum
}

/// Time window for an impulse response: rising over `pre` samples before time zero,
/// then flat for `length` samples, the last part of which are faded out.
struct Window {
    pre: usize,
    taper: Vec<f64>,
}

impl Window {
    fn new(pre: usize, length: usize) -> Self {
        let fade = ((FADE_OUT * length as f64) as usize).max(1);
        let mut taper = Vec::with_capacity(pre + length);
        taper.extend((0..pre).map(|i| raised_cosine(i, pre)));
        taper.extend(std::iter::repeat_n(1.0, length - fade));
        taper.extend((0..fade).map(|i| 1.0 - raised_cosine(i, fade)));
        Self { pre, taper }
    }

    fn len(&self) -> usize {
        self.taper.len()
    }
}

/// Number of samples per averaging interval below which the spectrum is evaluated at
/// that many frequencies within the interval (see `Zoom`) rather than taken from the
/// FFT bins falling into it.
const INTERVAL_SAMPLES: usize = 8;
/// Stopband attenuation of the `Zoom` low-pass filter, in dB (also its passband ripple).
const ZOOM_ATTENUATION: f64 = 120.0;

/// Modified Bessel function of the first kind, order zero.
fn bessel_i0(x: f64) -> f64 {
    let (mut sum, mut term, mut k) = (1.0, 1.0, 1.0);
    let q = x * x / 4.0;
    while term > 1e-17 * sum {
        term *= q / (k * k);
        sum += term;
        k += 1.0;
    }
    sum
}

/// Symmetric low-pass filter (Kaiser-windowed sinc) for decimating by `decimation`:
/// flat (to `ZOOM_ATTENUATION`) up to a quarter of the decimated sample rate, and
/// stopping from three quarters, where the aliases of the passband come from.
struct Lowpass {
    decimation: usize,
    /// `taps[n]` for `n >= 0` (the filter is symmetric).
    taps: Vec<f64>,
    /// The frequency response over the passband, at `TABLE_POINTS + 1` equally spaced
    /// frequencies (it is smooth, so this is interpolated).
    table: Vec<f64>,
}

impl Lowpass {
    const TABLE_POINTS: usize = 64;

    fn new(decimation: usize) -> Self {
        if decimation == 1 {
            return Self {
                decimation,
                taps: vec![1.0],
                table: vec![],
            };
        }
        let beta = 0.1102 * (ZOOM_ATTENUATION - 8.7);
        let cutoff = 0.5 / decimation as f64;
        // Kaiser's formula for the length, for a transition band of half the cutoff on
        // either side of it.
        let half = ((ZOOM_ATTENUATION - 8.0) / (2.285 * 2.0 * PI * cutoff)).ceil() as usize / 2 + 1;
        let i0 = bessel_i0(beta);
        let taps: Vec<f64> = (0..=half)
            .map(|n| {
                let x = n as f64;
                let sinc = if n == 0 {
                    2.0 * cutoff
                } else {
                    (2.0 * PI * cutoff * x).sin() / (PI * x)
                };
                let r = x / half as f64;
                sinc * bessel_i0(beta * (1.0 - r * r).max(0.0).sqrt()) / i0
            })
            .collect();
        let f_max = 0.25 / decimation as f64;
        let table = (0..=Self::TABLE_POINTS)
            .map(|i| Self::response(&taps, i as f64 / Self::TABLE_POINTS as f64 * f_max))
            .collect();
        Self {
            decimation,
            taps,
            table,
        }
    }

    /// The frequency response of a symmetric filter at `f` (cycles/sample).
    fn response(taps: &[f64], f: f64) -> f64 {
        let step = C64::from_polar(1.0, 2.0 * PI * f);
        let mut t = step;
        let mut sum = taps[0];
        for &tap in &taps[1..] {
            sum += 2.0 * tap * t.re;
            t *= step;
        }
        sum
    }

    /// The response at `frequencies` within the passband.
    fn responses(&self, frequencies: &[f64]) -> Vec<f64> {
        if self.decimation == 1 {
            return vec![1.0; frequencies.len()];
        }
        let points = Self::TABLE_POINTS;
        let f_max = 0.25 / self.decimation as f64;
        frequencies
            .iter()
            .map(|&f| {
                let x = (f / f_max * points as f64).clamp(0.0, points as f64);
                let i = (x as usize).min(points - 1);
                self.table[i] + (self.table[i + 1] - self.table[i]) * (x - i as f64)
            })
            .collect()
    }
}

/// Evaluates the DTFT of a long real signal at low frequencies, up to a quarter of the
/// decimated sample rate of `lowpass`: the signal is low-pass filtered and decimated,
/// which leaves aliases below `ZOOM_ATTENUATION`, and the filter's response is
/// divided out. This costs about 16 operations per sample of the signal, whatever the
/// decimation, plus the DTFT of the short decimated signal.
struct Zoom<'a> {
    lowpass: &'a Lowpass,
    /// The decimated signal, starting at sample `first * decimation`.
    decimated: Vec<f64>,
    first: i64,
}

impl<'a> Zoom<'a> {
    /// Decimation for a signal of `length` samples and frequencies up to `f_max`.
    fn decimation(f_max: f64, length: usize) -> usize {
        if f_max <= 0.0 {
            return 1;
        }
        ((0.25 / f_max) as usize).clamp(1, (length / 16).max(1))
    }

    fn new(x: &[f64], lowpass: &'a Lowpass) -> Self {
        let d = lowpass.decimation;
        if d == 1 {
            return Self {
                lowpass,
                decimated: x.to_vec(),
                first: 0,
            };
        }
        let taps = &lowpass.taps;
        let half = taps.len() - 1;
        let first = -((half / d) as i64);
        let last = ((x.len() - 1 + half) / d) as i64;
        // The signal with zeros on either side, so that the filter does not run over its
        // ends (the outermost outputs are centred up to `half` samples outside it).
        let mut padded = vec![0.0; x.len() + 4 * half];
        padded[2 * half..2 * half + x.len()].copy_from_slice(x);
        let decimated = (first..=last)
            .map(|m| {
                // Σ_k taps[|k|] x[centre + k]
                let centre = (m * d as i64 + 2 * half as i64) as usize;
                taps[0] * padded[centre]
                    + (1..=half)
                        .map(|k| taps[k] * (padded[centre - k] + padded[centre + k]))
                        .sum::<f64>()
            })
            .collect();
        Self {
            lowpass,
            decimated,
            first,
        }
    }

    /// `Σ_j x[j] exp(-2πi f j)`, given the filter's `response` at `f`.
    fn dtft(&self, f: f64, response: f64) -> C64 {
        let d = self.lowpass.decimation as f64;
        let step = C64::from_polar(1.0, -2.0 * PI * f * d);
        let mut t = C64::from_polar(1.0, -2.0 * PI * f * self.first as f64 * d);
        let mut sum = C64::new(0.0, 0.0);
        for &y in &self.decimated {
            sum += y * t;
            t *= step;
        }
        sum * d / response
    }
}

/// How one point of the grid is estimated from the spectrum of a segment.
enum Interval {
    /// From the FFT bins `lo..lo + n`, the first and last two weighted by the parts of
    /// their cells (half a bin spacing either side) within the interval (`edges`; the
    /// others have weight 1), which makes the average continuous in the bin positions.
    Bins {
        lo: usize,
        n: usize,
        edges: [f64; 4],
    },
    /// From the spectrum at `INTERVAL_SAMPLES` frequencies within the interval,
    /// starting at `exact_frequencies[first]`.
    Exact { first: usize },
}

impl Interval {
    fn len(&self) -> usize {
        match *self {
            Interval::Bins { n, .. } => n,
            Interval::Exact { .. } => INTERVAL_SAMPLES,
        }
    }

    /// The weight of the `j`-th sample.
    fn weight(&self, j: usize) -> f64 {
        match *self {
            Interval::Bins { n, edges, .. } => {
                if j < 2 {
                    edges[j]
                } else if j + 2 >= n {
                    edges[j + 4 - n]
                } else {
                    1.0
                }
            }
            Interval::Exact { .. } => 1.0,
        }
    }

    /// `Σ_i weight(i) weight(i + d)`.
    fn weight_autocorrelation(&self, d: usize) -> f64 {
        let n = self.len();
        let mut sum = (n - d) as f64;
        if let Interval::Bins { .. } = self {
            // The pairs (i, i + d) involving a weighted sample, counted once each.
            let weighted = |i: usize| i < 2 || i + 2 >= n;
            for i in [0, 1, n - 2, n - 1] {
                if i + d < n {
                    sum += self.weight(i) * self.weight(i + d) - 1.0;
                }
                if i >= d && !weighted(i - d) {
                    sum += self.weight(i - d) * self.weight(i) - 1.0;
                }
            }
        }
        sum
    }
}

/// Ratio of the upper edge of a grid interval to its centre frequency.
fn grid_half_width(points_per_decade: u32) -> f64 {
    10f64.powf(0.5 / points_per_decade as f64)
}

/// Averages the spectrum of a windowed segment over the frequency interval represented
/// by each point of a logarithmic grid: from the FFT bins (at the uniformly spaced `f`)
/// falling into the interval or, where there are few, from the spectrum evaluated at
/// `INTERVAL_SAMPLES` frequencies in it (`Zoom`).
struct GridAverager {
    f: Arc<Vec<f64>>,
    grid: Vec<f64>,
    /// Per grid point, with the difference of the mean frequencies of the upper and
    /// lower half of the interval (for the group delay estimate).
    intervals: Vec<(Interval, f64)>,
    exact_frequencies: Vec<f64>,
    lowpass: Lowpass,
    /// The low-pass filter's response at `exact_frequencies`.
    exact_response: Vec<f64>,
    /// For the noise of the averages: the spectral autocorrelation of the window,
    /// `Σ_n taper[n]² exp(-2πi ν n)`, at the bin spacings (`w2[d]` for
    /// `ν = d / n_spectrum`), and for each exact interval at multiples of its sample
    /// spacing.
    w2: Vec<C64>,
    w2_exact: Vec<Vec<C64>>,
}

impl GridAverager {
    fn new(
        f: Arc<Vec<f64>>,
        grid: Vec<f64>,
        points_per_decade: u32,
        taper: &[f64],
        fft: &Fft,
    ) -> Self {
        let half_width = grid_half_width(points_per_decade);
        let mut intervals = Vec::with_capacity(grid.len());
        let mut exact_frequencies = vec![];
        let mut exact_spacings = vec![];
        let df = f[1];
        for &centre in &grid {
            let (low, high) = (centre / half_width, centre * half_width);
            let lo = f.partition_point(|&v| v < low);
            let hi = f.partition_point(|&v| v < high);
            let (interval, frequencies): (Interval, Vec<f64>) = if hi - lo >= INTERVAL_SAMPLES {
                // The bins whose cells overlap the interval, with the overlap as weight.
                let (lo, hi) = (lo.saturating_sub(1), (hi + 1).min(f.len()));
                let weight = |k: usize| {
                    let cell = ((k as f64 - 0.5) * df, (k as f64 + 0.5) * df);
                    ((high.min(cell.1) - low.max(cell.0)) / df).clamp(0.0, 1.0)
                };
                let edges = [weight(lo), weight(lo + 1), weight(hi - 2), weight(hi - 1)];
                (
                    Interval::Bins {
                        lo,
                        n: hi - lo,
                        edges,
                    },
                    f[lo..hi].to_vec(),
                )
            } else {
                let spacing = (high - low) / INTERVAL_SAMPLES as f64;
                let first = exact_frequencies.len();
                let frequencies: Vec<f64> = (0..INTERVAL_SAMPLES)
                    .map(|p| low + (p as f64 + 0.5) * spacing)
                    .collect();
                exact_frequencies.extend(&frequencies);
                exact_spacings.push(spacing);
                (Interval::Exact { first }, frequencies)
            };
            // The difference of the (weighted) mean frequencies of the upper and lower
            // half.
            let middle = frequencies.len() / 2;
            let mean = |range: std::ops::Range<usize>| {
                let (mut sum, mut total) = (0.0, 0.0);
                for j in range {
                    sum += interval.weight(j) * frequencies[j];
                    total += interval.weight(j);
                }
                sum / total
            };
            let step = mean(middle..frequencies.len()) - mean(0..middle);
            intervals.push((interval, step));
        }
        let f_max = exact_frequencies.iter().copied().fold(0.0, f64::max);
        let lowpass = Lowpass::new(Zoom::decimation(f_max, taper.len()));
        let exact_response = lowpass.responses(&exact_frequencies);

        // The window's spectral autocorrelation.
        let squared: Vec<f64> = taper.iter().map(|t| t * t).collect();
        let mut padded = vec![0.0; fft.n];
        padded[..squared.len()].copy_from_slice(&squared);
        let mut w2 = vec![C64::default(); fft.bins()];
        fft.forward(&mut padded, &mut w2);
        let mut w2_exact = vec![];
        if !exact_spacings.is_empty() {
            let f_max =
                exact_spacings.iter().copied().fold(0.0, f64::max) * (INTERVAL_SAMPLES - 1) as f64;
            let lowpass = Lowpass::new(Zoom::decimation(f_max, taper.len()));
            let zoom = Zoom::new(&squared, &lowpass);
            for spacing in exact_spacings {
                let frequencies: Vec<f64> =
                    (0..INTERVAL_SAMPLES).map(|d| d as f64 * spacing).collect();
                let responses = lowpass.responses(&frequencies);
                w2_exact.push(
                    frequencies
                        .iter()
                        .zip(&responses)
                        .map(|(&f, &r)| zoom.dtft(f, r))
                        .collect(),
                );
            }
        }
        Self {
            f,
            grid,
            intervals,
            exact_frequencies,
            lowpass,
            exact_response,
            w2,
            w2_exact,
        }
    }

    /// The spectrum of `segment` (with time zero `shift` samples into it) at
    /// `exact_frequencies`.
    fn exact_values(&self, segment: &[f64], shift: i64) -> Vec<C64> {
        if self.exact_frequencies.is_empty() {
            return vec![];
        }
        let zoom = Zoom::new(segment, &self.lowpass);
        self.exact_frequencies
            .iter()
            .zip(&self.exact_response)
            .map(|(&f, &r)| zoom.dtft(f, r) * C64::from_polar(1.0, 2.0 * PI * f * shift as f64))
            .collect()
    }

    /// The samples of an interval and their frequencies.
    fn samples<'s>(
        &'s self,
        interval: &Interval,
        values: &'s [C64],
        exact: &'s [C64],
    ) -> (&'s [C64], &'s [f64]) {
        match *interval {
            Interval::Bins { lo, n, .. } => (&values[lo..lo + n], &self.f[lo..lo + n]),
            Interval::Exact { first } => (
                &exact[first..first + INTERVAL_SAMPLES],
                &self.exact_frequencies[first..first + INTERVAL_SAMPLES],
            ),
        }
    }

    /// Average the spectrum of `segment` (`values` at the bins; time zero `shift`
    /// samples into the segment) onto the grid. Returns the averages and the phase
    /// slopes compensated in them.
    fn average(&self, values: &[C64], segment: &[f64], shift: i64) -> (Vec<C64>, Vec<f64>) {
        let exact = self.exact_values(segment, shift);
        let mut result = Vec::with_capacity(self.grid.len());
        let mut slopes = Vec::with_capacity(self.grid.len());
        for ((interval, step), &centre) in self.intervals.iter().zip(&self.grid) {
            let (v, fv) = self.samples(interval, values, &exact);
            let n = v.len();
            let middle = n / 2;
            // The phase can change considerably over the interval (due to delays),
            // which would bias a complex average. Thus, estimate the local group delay
            // from the change in phase (relative to the value at the centre, to avoid
            // wrapping) between the lower and upper half of the interval, and
            // compensate for it in the average. (Averaging magnitude and phase
            // separately instead would be biased by noise.)
            let reference = v[middle].conj();
            let mean_phase = |range: std::ops::Range<usize>| {
                let (mut sum, mut total) = (0.0, 0.0);
                for j in range {
                    let weight = interval.weight(j);
                    sum += weight * (v[j] * reference).arg();
                    total += weight;
                }
                sum / total
            };
            let slope = (mean_phase(middle..n) - mean_phase(0..middle)) / step;
            let (mut sum, mut total) = (C64::new(0.0, 0.0), 0.0);
            for (j, (x, &f)) in v.iter().zip(fv).enumerate() {
                let weight = interval.weight(j);
                sum += weight * x * C64::from_polar(1.0, -slope * (f - centre));
                total += weight;
            }
            result.push(sum / total);
            slopes.push(slope);
        }
        (result, slopes)
    }

    /// The noise of `average()` for the noise samples `values` (at the bins) of a
    /// segment with time zero `shift` samples into it, given the phase slopes
    /// compensated in the average (or none).
    fn rms_average(&self, values: &[C64], shift: i64, slopes: Option<&[f64]>) -> Vec<f64> {
        let w2_0 = self.w2[0].re;
        self.intervals
            .iter()
            .zip(&self.grid)
            .enumerate()
            .map(|(g, ((interval, _), &centre))| {
                let slope = slopes.map_or(0.0, |s| s[g]);
                // The noise power per sample, the number of samples averaged and their
                // spacing in frequency.
                let n = interval.len();
                let total: f64 = (0..n).map(|j| interval.weight(j)).sum();
                let (power, spacing) = match *interval {
                    Interval::Bins { lo, .. } => (
                        (0..n)
                            .map(|j| interval.weight(j) * values[lo + j].norm_sqr())
                            .sum::<f64>()
                            / total,
                        self.f[1],
                    ),
                    Interval::Exact { first } => (
                        self.interpolate(|k| values[k].norm_sqr(), centre),
                        self.exact_frequencies[first + 1] - self.exact_frequencies[first],
                    ),
                };
                let w2 = |d: usize| match *interval {
                    Interval::Bins { .. } => self.w2[d],
                    Interval::Exact { first } => self.w2_exact[first / INTERVAL_SAMPLES][d],
                };
                // The variance of the compensated weighted mean of the correlated
                // samples, relative to their power: Σ over the pairs of their
                // correlation, which is that of the window as positioned in the segment
                // (`w2` is for the window at its start), with the phase compensation
                // applied.
                let phase_per_sample = (2.0 * PI * shift as f64 - slope) * spacing;
                let mut factor = interval.weight_autocorrelation(0) * w2_0;
                for d in 1..n {
                    let rotation = C64::from_polar(1.0, phase_per_sample * d as f64);
                    factor += 2.0 * interval.weight_autocorrelation(d) * (w2(d) * rotation).re;
                }
                (power * factor / (total * total) / w2_0).sqrt()
            })
            .collect()
    }

    /// Linear interpolation of `value` (sampled at `f`) at `x` (constant outside `f`).
    fn interpolate(&self, value: impl Fn(usize) -> f64, x: f64) -> f64 {
        let f = &self.f;
        let n = f.len();
        if x <= f[0] {
            return value(0);
        }
        if x >= f[n - 1] {
            return value(n - 1);
        }
        let j = f.partition_point(|&v| v <= x) - 1;
        let slope = (value(j + 1) - value(j)) / (f[j + 1] - f[j]);
        slope * (x - f[j]) + value(j)
    }
}

/// The valid part of the linear convolution of `a` with the kernel `b` (no longer than
/// `a`), with FFTs of a length of at least `a.len()`.
fn convolve_valid(fft: &Fft, a: &[f64], b: &[f64]) -> Vec<f64> {
    let (mut x, mut y) = (vec![0.0; fft.n], vec![0.0; fft.n]);
    x[..a.len()].copy_from_slice(a);
    y[..b.len()].copy_from_slice(b);
    let (mut xs, mut ys) = (
        vec![C64::default(); fft.bins()],
        vec![C64::default(); fft.bins()],
    );
    fft.forward(&mut x, &mut xs);
    fft.forward(&mut y, &mut ys);
    xs.iter_mut().zip(&ys).for_each(|(x, y)| *x *= y);
    fft.inverse(&mut xs, &mut x);
    x[b.len() - 1..a.len()].to_vec()
}

/// A gap of lost data, and how `Context::fill_gaps()` models the response there.
struct GapModel {
    /// The record index of the first lost sample, their number, and the record indices
    /// of the samples before and after the gap, between which the interpolation
    /// replacing them was drawn (see `Gaps`).
    start: usize,
    count: usize,
    left: usize,
    right: usize,
    /// The window of the impulse response around its peak (which is `window.pre`
    /// samples in) modelling the response at the gap, with the FFT for convolving it
    /// with the excitation around the gap, and the FFT for correcting the impulse
    /// response in the model region.
    window: Window,
    model_fft: Fft,
    correction_fft: Fft,
    /// The regularised inverse of the band limiting filter (the first `inverse_length`
    /// samples of the unity response) on the grid of `model_fft`: the impulse response
    /// is that filter's convolution with the system's, which the model must undo.
    inverse_length: usize,
    unity_inverse: Arc<Vec<C64>>,
}

/// Samples of the unity response inverted for the gap models (its main lobe and the
/// ringing of the upper band edge; the lower one's is longer but only matters near it),
/// and the regularisation of the inverse.
const UNITY_INVERSE_LENGTH: usize = 8192;
const UNITY_INVERSE_REGULARISATION: f64 = 1e-3;

/// The gaps of lost data of a run, for `Context::fill_gaps()`.
struct GapFill {
    gaps: Gaps,
    models: Vec<GapModel>,
    /// The region of the impulse response (relative to its peak) which the models read.
    region_start: i64,
    region_length: usize,
}

impl GapFill {
    /// For the gaps (start, stop) relative to the sweep start at `offset` in a record of
    /// `record_length` samples; `unity` is the deconvolver's unity response.
    fn new(
        context: &Context,
        run_gaps: &[(i64, i64)],
        offset: i64,
        record_length: usize,
        unity: &[f64],
    ) -> Self {
        let (pre, n_window) = (context.windows[0].pre, context.n_window());
        let absolute: Vec<(usize, usize)> = run_gaps
            .iter()
            .map(|&(a, b)| ((a + offset) as usize, (b + offset) as usize))
            .collect();
        let gaps = Gaps::new(&absolute, record_length);
        let (growth, f1) = (context.sweep.growth(), context.sweep.f_start());
        // The relative width of a grid interval.
        let half_width = grid_half_width(context.points_per_decade);
        let width = half_width - 1.0 / half_width;
        let sizes: Vec<(usize, usize)> = run_gaps
            .iter()
            .map(|&(start, stop)| {
                // The response is smoothed over the grid interval at the frequency of
                // the gap, or more widely if the gap covers more than a quarter of the
                // sweep's time in the interval (for the iteration to converge).
                let count = (stop - start) as f64;
                let f = f1 * (growth * (start + stop) as f64 / 2.0).exp();
                let length = (1.0 / (width * f)).min(0.25 / (count * growth * f));
                let length = (length as usize).clamp(64, n_window.max(64));
                ((length / 4).clamp(16, pre.max(16)), length)
            })
            .collect();
        let region_start = -(sizes.iter().map(|s| s.0).max().unwrap() as i64);
        let region_length = (-region_start) as usize + sizes.iter().map(|s| s.1).max().unwrap();
        let mut ffts: HashMap<usize, Fft> = HashMap::new();
        let mut fft = |n: usize| {
            ffts.entry(fast_length(n))
                .or_insert_with_key(|&n| Fft::new(n))
                .clone()
        };
        let mut inverses: HashMap<(usize, usize), Arc<Vec<C64>>> = HashMap::new();
        let models = gaps
            .gaps
            .iter()
            .zip(sizes)
            .map(|(&(start, count, left, right), (pre, length))| {
                let window = Window::new(pre, length);
                let inverse_length = UNITY_INVERSE_LENGTH.min(window.len());
                let model_fft = fft(count + 1 + window.len() + 2 * inverse_length);
                let correction_fft = fft(region_length + count);
                let unity_inverse = inverses
                    .entry((model_fft.n, inverse_length))
                    .or_insert_with(|| {
                        let mut u = vec![0.0; model_fft.n];
                        u[..inverse_length].copy_from_slice(&unity[..inverse_length]);
                        let mut spectrum = vec![C64::default(); model_fft.bins()];
                        model_fft.forward(&mut u, &mut spectrum);
                        for s in &mut spectrum {
                            *s = s.conj() / (s.norm_sqr() + UNITY_INVERSE_REGULARISATION);
                        }
                        Arc::new(spectrum)
                    })
                    .clone();
                GapModel {
                    start,
                    count,
                    left,
                    right,
                    window,
                    model_fft,
                    correction_fft,
                    inverse_length,
                    unity_inverse,
                }
            })
            .collect();
        Self {
            gaps,
            models,
            region_start,
            region_length,
        }
    }
}

/// The samples in the gaps (start, stop) of a record of length `n`, and the linear
/// interpolation from the neighbouring samples which replaces lost data there: the
/// straight line from the sample before the gap to the one after it, or that sample
/// alone at the ends of the record.
struct Gaps {
    /// Per gap: (first sample, count, sample before, sample after).
    gaps: Vec<(usize, usize, usize, usize)>,
}

impl Gaps {
    fn new(gaps: &[(usize, usize)], n: usize) -> Self {
        let gaps = gaps
            .iter()
            .map(|&(start, stop)| {
                let left = if start > 0 {
                    start - 1
                } else {
                    stop.min(n - 1)
                };
                let right = if stop < n {
                    stop
                } else {
                    start.saturating_sub(1)
                };
                (start, stop - start, left, right)
            })
            .collect();
        Self { gaps }
    }

    /// Interpolate the gaps of `x`.
    fn interpolate(&self, x: &mut [f64]) {
        for &(start, count, left, right) in &self.gaps {
            let left_value = x[left];
            let slope = (x[right] - left_value) / (count + 1) as f64;
            for j in 0..count {
                x[start + j] = slope * (j + 1) as f64 + left_value;
            }
        }
    }
}

/// The cached averages of the windowed unity response, by (window, delay).
type UnityAverages = Mutex<HashMap<(usize, i64), Arc<Vec<C64>>>>;

/// Deconvolves records with the sweep.
struct Deconvolver {
    fft: Fft,
    amplitude: f64,
    inverse: Vec<C64>,
    /// The (band-limited) impulse response obtained for a unity-gain system.
    unity: Vec<f64>,
    peak_delay: i64,
    /// The impulse response of the inverse filter (essentially the time-reversed
    /// sweep, ending around index 0).
    inverse_ir: Vec<f64>,
    /// Averages of the windowed unity response, by (window, delay): the same delays
    /// recur across channels and runs.
    unity_averages: UnityAverages,
}

impl Deconvolver {
    fn new(sweep: &Sweep, excitation: &[f64], n_fft: usize) -> Self {
        let fft = Fft::new(n_fft);
        let bins = fft.bins();
        let amplitude = sweep.amplitude;
        let (spectrum, band) = rayon::join(
            || {
                let mut x = vec![0.0; n_fft];
                x[..excitation.len()]
                    .par_iter_mut()
                    .zip(excitation)
                    .for_each(|(x, &e)| *x = e / amplitude);
                let mut spectrum = vec![C64::default(); bins];
                fft.forward(&mut x, &mut spectrum);
                spectrum
            },
            || {
                // Limit the band with a minimum phase filter, as the long and acausal
                // components of a zero phase one would be cut off by the time windows.
                let (f1, f2) = (sweep.f_start(), sweep.f_stop());
                let magnitude: Vec<f64> = (0..bins)
                    .into_par_iter()
                    .map(|k| band_window(k as f64 / n_fft as f64, f1, f2))
                    .collect();
                minimum_phase(&fft, &magnitude)
            },
        );
        // Expected power spectral density of the sweep (stationary phase approximation).
        let growth = sweep.growth();
        let expected = |k: usize| 1.0 / (4.0 * growth * (k.max(1) as f64 / n_fft as f64));
        let inverse: Vec<C64> = (0..bins)
            .into_par_iter()
            .map(|k| {
                let s = spectrum[k];
                band[k] * s.conj() / (s.norm_sqr() + REGULARISATION * expected(k))
            })
            .collect();
        let (unity, inverse_ir) = rayon::join(
            || {
                let mut product: Vec<C64> = inverse
                    .par_iter()
                    .zip(&spectrum)
                    .map(|(a, b)| a * b)
                    .collect();
                let mut unity = vec![0.0; n_fft];
                fft.inverse(&mut product, &mut unity);
                unity
            },
            || {
                let mut spectrum = inverse.clone();
                let mut inverse_ir = vec![0.0; n_fft];
                fft.inverse(&mut spectrum, &mut inverse_ir);
                inverse_ir
            },
        );
        let peak_delay = argmax_abs(&unity[..n_fft / 2]) as i64;
        Self {
            fft,
            amplitude,
            inverse,
            unity,
            peak_delay,
            inverse_ir,
            unity_averages: Mutex::new(HashMap::new()),
        }
    }

    /// Deconvolve `record`, in which the sweep starts at `start` (if known), into
    /// `buffers.h`.
    ///
    /// Steps at the ends of the record would show up in the impulse response, so the
    /// record is taken relative to the level before the sweep, and faded in and out.
    fn deconvolve(&self, record: &[f64], start: Option<usize>, buffers: &mut Buffers) {
        let Buffers { h, work, spectrum } = buffers;
        let n = record.len();
        let mean_length = start.map_or(n, |s| s.max(1));
        let mean = record[..mean_length].iter().sum::<f64>() / mean_length as f64;
        work[..n]
            .iter_mut()
            .zip(record)
            .for_each(|(w, &r)| *w = r - mean);
        if let Some(start) = start {
            let fade = (start / 2).min(n / 100);
            for i in 0..fade {
                let ramp = raised_cosine(i, fade);
                work[i] *= ramp;
                work[n - 1 - i] *= ramp;
            }
        }
        let scale = self.amplitude;
        work[..n].iter_mut().for_each(|w| *w /= scale);
        work[n..].fill(0.0);
        self.deconvolve_padded(work, spectrum, h);
    }

    /// Deconvolve the full-length `work` (already divided by the amplitude) into `out`.
    fn deconvolve_padded(&self, work: &mut [f64], spectrum: &mut [C64], out: &mut [f64]) {
        self.fft.forward(work, spectrum);
        self.apply_inverse(spectrum);
        self.fft.inverse(spectrum, out);
    }

    /// Deconvolve the full-length `work` (already divided by the amplitude) in place.
    fn deconvolve_in_place(&self, work: &mut [f64], spectrum: &mut [C64]) {
        self.fft.forward(work, spectrum);
        self.apply_inverse(spectrum);
        self.fft.inverse(spectrum, work);
    }

    fn apply_inverse(&self, spectrum: &mut [C64]) {
        spectrum
            .iter_mut()
            .zip(&self.inverse)
            .for_each(|(s, inv)| *s *= inv);
    }
}

/// Buffers of the size of the deconvolution, for one channel at a time.
struct Buffers {
    h: Vec<f64>,
    work: Vec<f64>,
    spectrum: Vec<C64>,
}

impl Buffers {
    fn new(n_fft: usize) -> Self {
        Self {
            h: vec![0.0; n_fft],
            work: vec![0.0; n_fft],
            spectrum: vec![C64::default(); n_fft / 2 + 1],
        }
    }

    /// Bytes needed per channel in flight: the buffers, and about what the spectra of
    /// impulse response segments (`n_spectrum` points) allocated during the analysis
    /// take.
    fn size(n_fft: usize, n_spectrum: usize) -> usize {
        8 * (3 * n_fft + 6 * n_spectrum)
    }
}

/// What is common to the analysis of all channels and runs.
struct Context<'a> {
    sweep: &'a Sweep,
    excitation: Vec<f64>,
    /// The channel containing the stimulus directly.
    reference: usize,
    batch_size: usize,
    points_per_decade: u32,
    /// The fundamental's window, followed by those of `harmonic_orders`.
    windows: Vec<Window>,
    harmonic_orders: Vec<usize>,
    /// Per harmonic, the fundamental frequencies at which it is available.
    harmonic_grids: Vec<Vec<f64>>,
    /// Each window's grid of output frequencies, and the averaging onto it.
    averagers: Vec<GridAverager>,
    fft: Fft,
    /// Start of the noise windows, relative to the sweep start.
    noise_start: i64,
    /// The range of the impulse responses returned, relative to the sweep start.
    ir_start: i64,
    ir_stop: i64,
}

impl<'a> Context<'a> {
    fn new(
        sweep: &'a Sweep,
        settings: &Settings,
        reference: usize,
        batch_size: usize,
    ) -> Result<Self, String> {
        let ts = sweep.sample_period;
        let (f1, f2) = (sweep.f_start(), sweep.f_stop());

        // Window parameters (in samples). The windows rise smoothly over `pre` samples
        // before time zero of the respective impulse response: sharp edges would mix the
        // response near the band edges into the whole band. They are limited by the
        // spacing to the (earlier) impulse response of the next higher harmonic.
        let n_window = ((settings.ir_window / ts).round_ties_even() as usize).max(16);
        let pre = (0.4 * sweep.harmonic_delay(2.0)).clamp(32.0, (n_window / 2) as f64) as usize;
        let mut windows = vec![Window::new(pre, n_window)];
        let mut harmonic_orders = vec![];
        let mut end = -(pre as i64);
        for k in 2..=settings.max_harmonic as usize {
            let delay = sweep.harmonic_delay(k as f64);
            let harmonic_pre = (0.3 * (sweep.harmonic_delay((k + 1) as f64) - delay)) as i64;
            let length = (end as f64 + delay) as i64;
            if harmonic_pre < 4 || length < 16 || k as f64 * f1 >= f2 {
                break;
            }
            windows.push(Window::new(harmonic_pre as usize, length as usize));
            harmonic_orders.push(k);
            end = (-delay) as i64 - harmonic_pre;
        }
        let max_taper = windows.iter().map(Window::len).max().unwrap();
        let n_spectrum = fast_length(2 * max_taper);
        let f_spectrum: Arc<Vec<f64>> = Arc::new(
            (0..n_spectrum / 2 + 1)
                .map(|k| k as f64 / n_spectrum as f64)
                .collect(),
        );

        // Logarithmic frequency grid inside the analysis band.
        let f_lo = f1 * 2f64.powf(BAND_EDGE_TAPER);
        let f_hi = f2 * 2f64.powf(-BAND_EDGE_TAPER);
        if f_lo >= f_hi {
            return Err("Frequency range too narrow".into());
        }
        let points_per_decade = settings.points_per_decade;
        let n_grid =
            (((f_hi / f_lo).log10() * points_per_decade as f64).ceil() as usize + 1).max(2);
        let grid = geomspace(f_lo, f_hi, n_grid);
        // The harmonics only cover output frequencies from k times the start frequency,
        // leading to an additional band edge there.
        let harmonic_grids: Vec<Vec<f64>> = harmonic_orders
            .iter()
            .map(|&k| {
                grid.iter()
                    .copied()
                    .filter(|&g| {
                        k as f64 * g <= f_hi && g >= f_lo * 2f64.powf(2.0 * BAND_EDGE_TAPER)
                    })
                    .collect()
            })
            .collect();
        let fft = Fft::new(n_spectrum);
        let mut averagers = vec![GridAverager::new(
            f_spectrum.clone(),
            grid,
            points_per_decade,
            &windows[0].taper,
            &fft,
        )];
        for ((&k, g), window) in harmonic_orders
            .iter()
            .zip(&harmonic_grids)
            .zip(&windows[1..])
        {
            let output: Vec<f64> = g.iter().map(|f| k as f64 * f).collect();
            averagers.push(GridAverager::new(
                f_spectrum.clone(),
                output,
                points_per_decade,
                &window.taper,
                &fft,
            ));
        }

        let noise_start = (n_window - pre) as i64;
        Ok(Self {
            sweep,
            excitation: sweep.excitation(),
            reference,
            batch_size,
            points_per_decade,
            windows,
            harmonic_orders,
            harmonic_grids,
            averagers,
            fft,
            noise_start,
            ir_start: (-(pre as i64)).min(end),
            ir_stop: noise_start + max_taper as i64,
        })
    }

    fn n_spectrum(&self) -> usize {
        self.fft.n
    }

    /// Length of the fundamental's window after time zero.
    fn n_window(&self) -> usize {
        self.windows[0].len() - self.windows[0].pre
    }

    fn max_taper(&self) -> usize {
        self.windows.iter().map(Window::len).max().unwrap()
    }

    /// The FFT length for deconvolving a record of `record_length` samples: the record
    /// plus the range of the impulse response which is used, and the longest window. The
    /// rest of the record and the higher harmonics wrap around, but outside that range,
    /// as the sweep starts at a non-negative offset and ends within the record.
    fn n_fft(&self, record_length: usize) -> usize {
        let margin = (-self.ir_start).max(self.ir_stop) as usize + self.max_taper();
        fast_length(record_length + margin)
    }

    /// Spectrum of an impulse response segment (times its taper), with time zero
    /// `shift` samples into the segment: the zero-padded segment is rotated to put time
    /// zero at index 0, which is the same as multiplying the spectrum by
    /// exp(2πi f shift).
    fn spectrum(&self, segment: &[f64], shift: i64) -> Vec<C64> {
        let n = self.n_spectrum();
        let mut real = vec![0.0; n];
        let start = (-shift).rem_euclid(n as i64) as usize;
        let head = segment.len().min(n - start);
        real[start..start + head].copy_from_slice(&segment[..head]);
        real[..segment.len() - head].copy_from_slice(&segment[head..]);
        let mut out = vec![C64::default(); self.fft.bins()];
        self.fft.forward(&mut real, &mut out);
        out
    }

    /// `h` from `start` (wrapping) over the length of `window`, times its taper.
    fn windowed(&self, h: &[f64], start: i64, window: usize) -> Vec<f64> {
        let taper = &self.windows[window].taper;
        let mut segment = vec![0.0; taper.len()];
        take_wrapped(h, start, &mut segment);
        segment.iter_mut().zip(taper).for_each(|(s, t)| *s *= t);
        segment
    }

    /// Spectrum of the impulse response of a unity-gain system with bulk delay `delay`,
    /// windowed like a response with `window`.
    fn unity_spectrum(&self, deconvolver: &Deconvolver, window: usize, delay: i64) -> Vec<C64> {
        let pre = self.windows[window].pre as i64;
        let windowed = self.windowed(&deconvolver.unity, -pre - delay, window);
        self.spectrum(&windowed, pre + delay)
    }

    /// `unity_spectrum()` averaged onto the window's grid (cached).
    fn unity_average(&self, deconvolver: &Deconvolver, window: usize, delay: i64) -> Arc<Vec<C64>> {
        let key = (window, delay);
        if let Some(average) = deconvolver.unity_averages.lock().unwrap().get(&key) {
            return average.clone();
        }
        let pre = self.windows[window].pre as i64;
        let windowed = self.windowed(&deconvolver.unity, -pre - delay, window);
        let values = self.spectrum(&windowed, pre + delay);
        let (average, _) = self.averagers[window].average(&values, &windowed, pre + delay);
        let average = Arc::new(average);
        deconvolver
            .unity_averages
            .lock()
            .unwrap()
            .insert(key, average.clone());
        average
    }

    /// Response on the grid of `window` from the impulse response `h` with time zero at
    /// `start + fraction`, normalised by the same windowing of the unity response with
    /// the same bulk delay. With `noise`, also the noise estimates for all windows,
    /// from the impulse response following `window`. Returns the response, the noise
    /// estimates, and the bulk delay found (in samples).
    fn response(
        &self,
        deconvolver: &Deconvolver,
        h: &[f64],
        start: i64,
        window: usize,
        fraction: f64,
        noise: bool,
    ) -> (Vec<C64>, Vec<Vec<f64>>, i64) {
        let pre = self.windows[window].pre;
        let windowed = self.windowed(h, start - pre as i64, window);
        // The bulk delay of the response, beyond that of the band limiting filter.
        let delay = argmax_abs(&windowed[pre..]) as i64 - deconvolver.peak_delay;
        // Remove the bulk delay before averaging over frequency (and restore it after).
        let shift = pre as i64 + delay;
        let values = self.spectrum(&windowed, shift);
        let averager = &self.averagers[window];
        let (mut result, slopes) = averager.average(&values, &windowed, shift);
        let unity_average = self.unity_average(deconvolver, window, delay);
        for ((r, &u), &f) in result
            .iter_mut()
            .zip(unity_average.iter())
            .zip(&averager.grid)
        {
            let rotation = -2.0 * PI * f * (delay as f64 - fraction);
            *r = *r / u * C64::from_polar(1.0, rotation);
        }
        let mut estimates = vec![];
        if noise {
            let unity_values = self.unity_spectrum(deconvolver, window, delay);
            // The following part of the impulse response contains the noise, as well as
            // the continuation of the band limiting filter response, which is subtracted
            // using the response estimate.
            let estimate: Vec<C64> = values
                .iter()
                .zip(&unity_values)
                .map(|(v, u)| {
                    let e = v / u;
                    if e.is_finite() {
                        e
                    } else {
                        C64::default()
                    }
                })
                .collect();
            for noise_window in 0..self.windows.len() {
                let mut noise_values = self.spectrum(
                    &self.windowed(h, start + self.noise_start, noise_window),
                    shift,
                );
                let continuation = self.spectrum(
                    &self.windowed(&deconvolver.unity, self.noise_start - delay, noise_window),
                    shift,
                );
                for ((n, &c), (&e, &u)) in noise_values
                    .iter_mut()
                    .zip(&continuation)
                    .zip(estimate.iter().zip(&unity_values))
                {
                    *n -= e * c;
                    // The estimate carries the noise of the response window, which the
                    // subtraction adds to that of the noise window; take it out of the
                    // power.
                    let added = (c / u).norm_sqr();
                    *n /= (1.0 + if added.is_finite() { added } else { 0.0 }).sqrt();
                }
                // (The phase slopes compensated in the average decorrelate the samples;
                // those of the harmonics' responses are not known here.)
                let noise_slopes = (noise_window == window).then_some(&slopes[..]);
                let mut noise_average =
                    self.averagers[noise_window].rms_average(&noise_values, shift, noise_slopes);
                // Relative to the gain of the window, as for the response.
                let gain = self.unity_average(deconvolver, noise_window, delay);
                noise_average
                    .iter_mut()
                    .zip(gain.iter())
                    .for_each(|(n, g)| *n /= g.norm());
                estimates.push(noise_average);
            }
        }
        (result, estimates, delay)
    }

    /// Correct the impulse response `buffers.h` of a record for its lost samples, which
    /// have been interpolated linearly.
    ///
    /// What the interpolation removed is a burst, which the deconvolution spreads along
    /// a chirp through the impulse response, where it swamps the harmonics and the
    /// noise estimate at the frequencies at which the chirp passes their windows, and
    /// biases the response at the frequency of the sweep at the time of the gap. The
    /// linear response to the stimulus there is known from the impulse response (and
    /// the stimulus exactly), so this models what the interpolation removed, and adds
    /// its impulse response back. The model is the impulse response around its peak,
    /// windowed to the resolution of the grid at the frequency of the gap (see
    /// `GapFill`): finer than that, the data at the frequency of the gap is mostly the
    /// lost data itself. As the impulse response is itself biased by what is missing,
    /// this is repeated; the correction is only computed within the model region until
    /// the fill has converged.
    fn fill_gaps(&self, deconvolver: &Deconvolver, run: &RunPrep, buffers: &mut Buffers) {
        let fill = run.gap_fill.as_ref().unwrap();
        let offset = run.offset;
        let Buffers { h, work, spectrum } = buffers;
        // The peak of the impulse response (the bulk delay), as in `response()`, and the
        // model region around it.
        let pre = self.windows[0].pre;
        let segment = self.windowed(h, offset - pre as i64, 0);
        let peak = argmax_abs(&segment[pre..]) as i64;
        let region_start = offset + peak + fill.region_start;
        let mut original = vec![0.0; fill.region_length];
        take_wrapped(h, region_start, &mut original);
        let mut region = original.clone();
        let excitation = &self.excitation;
        let stimulus = |u: i64| {
            let i = u - offset;
            if (0..excitation.len() as i64).contains(&i) {
                excitation[i as usize]
            } else {
                0.0
            }
        };
        let mut removed: Vec<(usize, f64)> = vec![];
        let mut previous: Vec<(usize, f64)> = vec![];
        for _ in 0..GAP_FILL_PASSES {
            removed.clear();
            for model in &fill.models {
                let taper = &model.window.taper;
                let first = (-(model.window.pre as i64) - fill.region_start) as usize;
                let fft = &model.model_fft;
                let mut windowed = vec![0.0; fft.n];
                for ((w, x), t) in windowed.iter_mut().zip(&region[first..]).zip(taper) {
                    *w = x * t;
                }
                // The kernel: the windowed impulse response with the band limiting
                // filter divided out, which is acausal by up to `inverse_length`
                // samples (wrapped around in the FFT).
                let mut spectrum = vec![C64::default(); fft.bins()];
                fft.forward(&mut windowed, &mut spectrum);
                for (s, u) in spectrum.iter_mut().zip(model.unity_inverse.iter()) {
                    *s *= u;
                }
                fft.inverse(&mut spectrum, &mut windowed);
                let w = model.inverse_length;
                let mut kernel = vec![0.0; taper.len() + 2 * w];
                take_wrapped(&windowed, -(w as i64), &mut kernel);
                // The model at t = start - 1 ..= start + count: the valid part of the
                // linear convolution of the excitation from u0 with the kernel, whose
                // first sample is at the lag `start_lag`.
                let start_lag = peak - (model.window.pre + w) as i64;
                let t0 = model.start as i64 - 1;
                let u0 = t0 - start_lag - (kernel.len() as i64 - 1);
                let slice: Vec<f64> = (0..model.count + 1 + kernel.len())
                    .map(|j| stimulus(u0 + j as i64))
                    .collect();
                let values = convolve_valid(fft, &slice, &kernel);
                // Minus the interpolation between the neighbours (see `Gaps`).
                let at = |t: usize| values[t + 1 - model.start];
                let left = at(model.left);
                let slope = (at(model.right) - left) / (model.count + 1) as f64;
                for j in 0..model.count {
                    let line = slope * (j + 1) as f64 + left;
                    removed.push((model.start + j, values[j + 1] - line));
                }
            }
            if !previous.is_empty() {
                let change = removed
                    .iter()
                    .zip(&previous)
                    .map(|(a, b)| (a.1 - b.1).abs())
                    .fold(0.0, f64::max);
                let scale = removed.iter().map(|a| a.1.abs()).fold(0.0, f64::max);
                if change <= GAP_FILL_TOLERANCE * scale {
                    break;
                }
            }
            // The correction of the impulse response within the model region: the
            // deconvolution of what was removed.
            region.copy_from_slice(&original);
            let mut index = 0;
            for model in &fill.models {
                let burst: Vec<f64> = removed[index..index + model.count]
                    .iter()
                    .map(|&(_, v)| v / deconvolver.amplitude)
                    .collect();
                index += model.count;
                let mut inverse = vec![0.0; fill.region_length + model.count - 1];
                let base = region_start - model.start as i64 - (model.count as i64 - 1);
                take_wrapped(&deconvolver.inverse_ir, base, &mut inverse);
                let correction = convolve_valid(&model.correction_fft, &inverse, &burst);
                region
                    .iter_mut()
                    .zip(&correction)
                    .for_each(|(x, c)| *x += c);
            }
            previous.clone_from(&removed);
        }
        // The final correction, of the whole impulse response.
        work.fill(0.0);
        for &(i, r) in &removed {
            work[i] = r / deconvolver.amplitude;
        }
        deconvolver.deconvolve_in_place(work, spectrum);
        work.iter_mut().zip(h.iter()).for_each(|(w, &h)| *w += h);
        std::mem::swap(h, work);
    }

    /// Locate the sweep in a run (`records` are its channels) unless `offset` is known,
    /// and prepare what the analysis of its channels shares. `gaps` are the sample
    /// ranges (start, stop) of lost data in the record.
    fn prepare_run(
        &self,
        deconvolver: &Deconvolver,
        records: &[&[f64]],
        offset: Option<i64>,
        gaps: &[(i64, i64)],
        buffers: &mut Buffers,
    ) -> Result<RunPrep, String> {
        let sweep = self.sweep;
        let record_length = records[0].len();
        let mut warnings = vec![];
        let offset = match offset {
            Some(offset) => offset,
            None => {
                deconvolver.deconvolve(records[self.reference], None, buffers);
                find_sweep_start(
                    &buffers.h,
                    record_length,
                    deconvolver,
                    self.batch_size,
                    &mut warnings,
                )?
            }
        };
        if offset < 0 {
            return Err("The sweep started before the capture".into());
        }
        let after_sweep = record_length as i64 - (offset + sweep.length as i64);
        if after_sweep < 0 {
            return Err("The sweep was not captured completely".into());
        }
        if after_sweep < self.n_window() as i64 {
            warnings.push("Capture ended before the end of the impulse response window".into());
        }
        // The noise windows collect the noise from the following sweep length of the
        // record.
        let has_noise: Vec<bool> = self
            .windows
            .iter()
            .map(|w| {
                offset + self.noise_start + (w.len() + sweep.length) as i64 <= record_length as i64
            })
            .collect();
        // Lost data during the sweep, relative to the start of the sweep.
        let run_gaps: Vec<(i64, i64)> = gaps
            .iter()
            .filter_map(|&(start, stop)| {
                let start = (start - offset).clamp(0, sweep.length as i64);
                let stop = (stop - offset).clamp(0, sweep.length as i64);
                (stop > start).then_some((start, stop))
            })
            .collect();
        // The frequency of the sweep at the middle of each gap.
        let gap_frequencies = run_gaps
            .iter()
            .map(|&(start, stop)| {
                sweep.f_start() * (sweep.growth() * (start + stop) as f64 / 2.0).exp()
            })
            .collect();
        let noise_affected = self
            .windows
            .iter()
            .zip(&self.averagers)
            .map(|(w, a)| {
                affected(
                    &a.grid,
                    &run_gaps,
                    self.noise_start,
                    self.noise_start + w.len() as i64,
                    sweep,
                )
            })
            .collect();
        let harmonic_affected = self
            .harmonic_orders
            .iter()
            .zip(&self.windows[1..])
            .zip(&self.averagers[1..])
            .map(|((&k, w), a)| {
                let lag_start = -sweep.harmonic_delay(k as f64) - w.pre as f64;
                affected(
                    &a.grid,
                    &run_gaps,
                    lag_start.floor() as i64,
                    (lag_start + w.len() as f64).ceil() as i64,
                    sweep,
                )
            })
            .collect();
        let mut stimulus = vec![0.0; record_length];
        let offset_usize = offset as usize;
        stimulus[offset_usize..offset_usize + sweep.length].copy_from_slice(&self.excitation);
        let mut gap_fill = None;
        if !run_gaps.is_empty() {
            let fill = GapFill::new(self, &run_gaps, offset, record_length, &deconvolver.unity);
            // Interpolated like the record, so that the difference is the interpolated
            // filter output.
            fill.gaps.interpolate(&mut stimulus);
            gap_fill = Some(fill);
        }
        let reference_output = records[self.reference]
            .iter()
            .zip(&stimulus)
            .map(|(r, s)| r - s)
            .collect();
        Ok(RunPrep {
            offset,
            gap_fill,
            reference_output,
            has_noise,
            noise_affected,
            harmonic_affected,
            gap_frequencies,
            warnings,
        })
    }

    /// Analyse one channel (`record`) of a prepared run.
    fn analyse_channel(
        &self,
        deconvolver: &Deconvolver,
        prep: &RunPrep,
        record: &[f64],
        buffers: &mut Buffers,
    ) -> ChannelResult {
        let offset = prep.offset;
        deconvolver.deconvolve(record, Some(offset as usize), buffers);
        if prep.gap_fill.is_some() {
            self.fill_gaps(deconvolver, prep, buffers);
        }
        let h = &buffers.h;
        let (response, mut estimates, _) = self.response(deconvolver, h, offset, 0, 0.0, true);
        for (i, estimate) in estimates.iter_mut().enumerate() {
            if prep.has_noise[i] {
                estimate
                    .iter_mut()
                    .zip(&prep.noise_affected[i])
                    .for_each(|(e, &a)| {
                        if a {
                            *e = f64::NAN;
                        }
                    });
            } else {
                estimate.fill(f64::NAN);
            }
        }
        let noise = estimates.remove(0);
        let harmonics: Vec<Vec<C64>> = self
            .harmonic_orders
            .iter()
            .enumerate()
            .map(|(i, &k)| {
                let delay = self.sweep.harmonic_delay(k as f64);
                let rounded = delay.round_ties_even();
                let mut harmonic = self
                    .response(
                        deconvolver,
                        h,
                        offset - rounded as i64,
                        i + 1,
                        rounded - delay,
                        false,
                    )
                    .0;
                // Left out where the window receives what remains of lost data (the
                // harmonic content there is not modelled by `fill_gaps()`).
                for (x, &a) in harmonic.iter_mut().zip(&prep.harmonic_affected[i]) {
                    if a {
                        *x = C64::new(f64::NAN, f64::NAN);
                    }
                }
                harmonic
            })
            .collect();
        let mut impulse_response = vec![0.0; (self.ir_stop - self.ir_start) as usize];
        take_wrapped(h, offset + self.ir_start, &mut impulse_response);
        ChannelResult {
            response,
            noise,
            harmonics,
            harmonic_noise: estimates,
            impulse_response,
        }
    }

    /// The results, averaged over the runs.
    fn analysis(
        &self,
        results: &[Vec<ChannelResult>],
        offsets: Vec<i64>,
        noise_available: bool,
        gap_frequencies: Vec<f64>,
        warnings: Vec<String>,
    ) -> Analysis {
        let n_runs = results.len();
        let channels = 0..results[0].len();
        let n_harmonics = self.harmonic_orders.len();
        let ir_length = (self.ir_stop - self.ir_start) as usize;
        let harmonic_windows = self
            .harmonic_orders
            .iter()
            .zip(&self.windows[1..])
            .map(|(&k, w)| {
                let delay = self.sweep.harmonic_delay(k as f64);
                (-delay - w.pre as f64, -delay + (w.len() - w.pre) as f64)
            })
            .collect();
        Analysis {
            frequencies: self.averagers[0].grid.clone(),
            responses: channels
                .clone()
                .map(|c| mean_over_runs(results, c, |r| &r.response))
                .collect(),
            noise: channels
                .clone()
                .map(|c| noise_over_runs(results, c, |r| &r.noise))
                .collect(),
            harmonic_orders: self.harmonic_orders.clone(),
            harmonic_frequencies: self.harmonic_grids.clone(),
            harmonics: (0..n_harmonics)
                .map(|i| {
                    channels
                        .clone()
                        .map(|c| mean_over_runs(results, c, |r| &r.harmonics[i]))
                        .collect()
                })
                .collect(),
            harmonic_noise: (0..n_harmonics)
                .map(|i| {
                    channels
                        .clone()
                        .map(|c| noise_over_runs(results, c, |r| &r.harmonic_noise[i]))
                        .collect()
                })
                .collect(),
            ir_start: self.ir_start,
            impulse_responses: channels
                .clone()
                .map(|c| {
                    let mut sum = vec![0.0; ir_length];
                    for run in results {
                        sum.iter_mut()
                            .zip(&run[c].impulse_response)
                            .for_each(|(s, v)| *s += v);
                    }
                    sum.iter().map(|s| s / n_runs as f64).collect()
                })
                .collect(),
            ir_window: (-(self.windows[0].pre as i64), self.n_window() as i64),
            noise_window: noise_available.then_some((
                self.noise_start,
                self.noise_start + self.windows[0].len() as i64,
            )),
            harmonic_windows,
            offsets,
            gap_frequencies,
            warnings,
        }
    }
}

/// What the analysis of each channel of a run needs.
struct RunPrep {
    offset: i64,
    /// The lost (interpolated) data during the sweep, if any.
    gap_fill: Option<GapFill>,
    /// The reference channel with the excitation subtracted.
    reference_output: Vec<f64>,
    /// Per window: whether a noise estimate is available, and at which of its
    /// frequencies it is left out because of lost data.
    has_noise: Vec<bool>,
    noise_affected: Vec<Vec<bool>>,
    /// Per harmonic: at which frequencies its response is left out because of lost
    /// data.
    harmonic_affected: Vec<Vec<bool>>,
    /// The frequency of the sweep at each gap.
    gap_frequencies: Vec<f64>,
    warnings: Vec<String>,
}

struct ChannelResult {
    response: Vec<C64>,
    noise: Vec<f64>,
    harmonics: Vec<Vec<C64>>,
    harmonic_noise: Vec<Vec<f64>>,
    impulse_response: Vec<f64>,
}

/// Locate the start of the sweep in the impulse response `h` of the reference channel.
fn find_sweep_start(
    h: &[f64],
    record_length: usize,
    deconvolver: &Deconvolver,
    batch_size: usize,
    warnings: &mut Vec<String>,
) -> Result<i64, String> {
    let peak = argmax_abs(&h[..record_length]);
    if h[peak].abs() < 0.1 * deconvolver.unity[deconvolver.peak_delay as usize].abs() {
        return Err("Sweep not found in the captured data".into());
    }
    let mut offset = peak as i64 - deconvolver.peak_delay;
    // The source is updated at batch boundaries, and captures start at one.
    let aligned = (offset as f64 / batch_size as f64).round_ties_even() as i64 * batch_size as i64;
    if aligned != offset {
        if (aligned - offset).abs() <= 2 {
            warnings.push(format!(
                "Sweep start found {} samples off the batch boundary; using the boundary",
                offset - aligned
            ));
            offset = aligned;
        } else {
            warnings.push(format!(
                "Sweep start not aligned to batch boundary (offset {offset} samples)"
            ));
        }
    }
    Ok(offset)
}

/// Which of the frequencies `f` read from a window of the impulse response at lags
/// `lag_start` to `lag_stop` (relative to the sweep start) receive the record at the
/// sample ranges `gaps` (relative to the sweep start).
///
/// The deconvolution places the record at time t and frequency f at the lag t - t_f,
/// where t_f is the time at which the sweep passes f (the inverse filter is essentially
/// the time-reversed sweep).
fn affected(
    f: &[f64],
    gaps: &[(i64, i64)],
    lag_start: i64,
    lag_stop: i64,
    sweep: &Sweep,
) -> Vec<bool> {
    let f1 = sweep.f_start();
    let growth = sweep.growth();
    let margin = 2f64.powf(GAP_MARGIN);
    let mut affected = vec![false; f.len()];
    for &(start, stop) in gaps {
        let low = f1 * (growth * (start - lag_stop) as f64).exp() / margin;
        let high = f1 * (growth * (stop - lag_start) as f64).exp() * margin;
        for (a, &f) in affected.iter_mut().zip(f) {
            *a |= f >= low && f <= high;
        }
    }
    affected
}

fn geomspace(start: f64, stop: f64, n: usize) -> Vec<f64> {
    let (log_start, log_stop) = (start.log10(), stop.log10());
    let step = (log_stop - log_start) / (n - 1) as f64;
    let mut grid: Vec<f64> = (0..n)
        .map(|i| 10f64.powf(i as f64 * step + log_start))
        .collect();
    grid[0] = start;
    grid[n - 1] = stop;
    grid
}

/// The mean of `get(result)` over the runs in which it has a value (NaN marks a value
/// left out).
fn mean_over_runs(
    results: &[Vec<ChannelResult>],
    channel: usize,
    get: impl Fn(&ChannelResult) -> &[C64],
) -> Vec<C64> {
    let n = get(&results[0][channel]).len();
    let mut sum = vec![C64::default(); n];
    let mut count = vec![0usize; n];
    for run in results {
        for ((s, c), v) in sum.iter_mut().zip(&mut count).zip(get(&run[channel])) {
            if v.is_finite() {
                *s += v;
                *c += 1;
            }
        }
    }
    sum.iter().zip(&count).map(|(s, &c)| s / c as f64).collect()
}

/// The noise of the average over the independent runs, from the runs with an estimate.
fn noise_over_runs(
    results: &[Vec<ChannelResult>],
    channel: usize,
    get: impl Fn(&ChannelResult) -> &[f64],
) -> Vec<f64> {
    let n_runs = results.len();
    let n = get(&results[0][channel]).len();
    (0..n)
        .map(|i| {
            let (mut sum, mut count) = (0.0, 0usize);
            for run in results {
                let v = get(&run[channel])[i];
                if v.is_finite() {
                    sum += v * v;
                    count += 1;
                }
            }
            (sum / count as f64 / n_runs as f64).sqrt()
        })
        .collect()
}

/// Estimate the responses of all channels to the sweep, averaged over several runs.
///
/// `runs[run][channel]` is the captured data, in volts, with lost data interpolated
/// linearly; `gaps[run]` the ranges (start, stop) of such samples. `reference` is the
/// channel containing the stimulus directly; `offsets` the start of the sweep in each
/// run, if known. The results include an additional channel: the reference channel
/// with the excitation subtracted.
pub fn analyse(
    runs: &[Vec<&[f64]>],
    sweep: &Sweep,
    reference: usize,
    batch_size: usize,
    settings: &Settings,
    offsets: Option<&[i64]>,
    gaps: Option<&[Vec<(i64, i64)>]>,
) -> Result<Analysis, String> {
    let n_runs = runs.len();
    if n_runs == 0 || runs[0].is_empty() || runs[0][0].is_empty() {
        return Err("No data".into());
    }
    let n_channels = runs[0].len() + 1;
    let context = Context::new(sweep, settings, reference, batch_size)?;

    // The runs are processed in groups of the same deconvolution FFT length (usually
    // all of them), each with one deconvolver.
    let mut groups: BTreeMap<usize, Vec<usize>> = BTreeMap::new();
    for (run, records) in runs.iter().enumerate() {
        groups
            .entry(context.n_fft(records[0].len()))
            .or_default()
            .push(run);
    }
    let mut results: Vec<Vec<ChannelResult>> = (0..n_runs).map(|_| vec![]).collect();
    let mut found_offsets = vec![0i64; n_runs];
    let mut warnings = vec![];
    let mut gap_frequencies = vec![];
    let mut noise_available = true;
    for (n_fft, group) in groups {
        let deconvolver = Deconvolver::new(sweep, &context.excitation, n_fft);
        let workers = (settings.memory / Buffers::size(n_fft, context.n_spectrum()))
            .clamp(1, rayon::current_num_threads());
        let pool = rayon::ThreadPoolBuilder::new()
            .num_threads(workers)
            .build()
            .map_err(|e| e.to_string())?;
        let new_buffers = || Buffers::new(n_fft);

        let preps: Vec<RunPrep> = pool.install(|| {
            group
                .par_iter()
                .map_init(new_buffers, |buffers, &run| {
                    context.prepare_run(
                        &deconvolver,
                        &runs[run],
                        offsets.map(|o| o[run]),
                        gaps.map_or(&[][..], |g| &g[run][..]),
                        buffers,
                    )
                })
                .collect::<Result<_, _>>()
        })?;
        for (&run, prep) in group.iter().zip(&preps) {
            found_offsets[run] = prep.offset;
            warnings.extend(prep.warnings.iter().cloned());
            gap_frequencies.extend(&prep.gap_frequencies);
            noise_available &= prep.has_noise[0];
        }

        // The channels of all runs of the group, in parallel.
        let tasks: Vec<(usize, usize)> = (0..group.len())
            .flat_map(|i| (0..n_channels).map(move |channel| (i, channel)))
            .collect();
        let channel_results: Vec<ChannelResult> = pool.install(|| {
            tasks
                .par_iter()
                .map_init(new_buffers, |buffers, &(i, channel)| {
                    let records = &runs[group[i]];
                    let record = records
                        .get(channel)
                        .copied()
                        .unwrap_or(&preps[i].reference_output);
                    context.analyse_channel(&deconvolver, &preps[i], record, buffers)
                })
                .collect()
        });
        let mut channel_results = channel_results.into_iter();
        for &run in &group {
            results[run] = channel_results.by_ref().take(n_channels).collect();
        }
    }

    if !noise_available {
        warnings.push("Capture too short for a noise estimate".into());
    }
    gap_frequencies.sort_by(f64::total_cmp);
    let mut unique = vec![];
    for w in warnings {
        if !unique.contains(&w) {
            unique.push(w);
        }
    }
    Ok(context.analysis(
        &results,
        found_offsets,
        noise_available,
        gap_frequencies,
        unique,
    ))
}
